// This file has been generated by Py++.

#ifndef _chaste_project_PyChaste_pde_classes_1_hpp__pyplusplus_wrapper
#define _chaste_project_PyChaste_pde_classes_1_hpp__pyplusplus_wrapper

void register_classes_1();

#endif//_chaste_project_PyChaste_pde_classes_1_hpp__pyplusplus_wrapper
