// This file has been generated by Py++.

#ifndef _chaste_project_PyChaste_pde_classes_3_hpp__pyplusplus_wrapper
#define _chaste_project_PyChaste_pde_classes_3_hpp__pyplusplus_wrapper

void register_classes_3();

#endif//_chaste_project_PyChaste_pde_classes_3_hpp__pyplusplus_wrapper
