namespace py = pybind11;

#ifndef AbstractPythonOdeSystemInformation_hpp__pyplusplus_wrapper
#define AbstractPythonOdeSystemInformation_hpp__pyplusplus_wrapper
void register_AbstractPythonOdeSystemInformation_class(py::module &m);
#endif // AbstractPythonOdeSystemInformation_hpp__pyplusplus_wrapper
