#ifndef AbstractOdeSystemInformation_hpp__pyplusplus_wrapper
#define AbstractOdeSystemInformation_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractOdeSystemInformation_class(py::module &m);
#endif // AbstractOdeSystemInformation_hpp__pyplusplus_wrapper
