#ifndef AbstractVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
#define AbstractVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractVertexBasedDivisionRule3_class(py::module &m);
#endif // AbstractVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
