namespace py = pybind11;

#ifndef AbstractGrowingDomainPdeModifier2_hpp__pyplusplus_wrapper
#define AbstractGrowingDomainPdeModifier2_hpp__pyplusplus_wrapper
void register_AbstractGrowingDomainPdeModifier2_class(py::module &m);
#endif // AbstractGrowingDomainPdeModifier2_hpp__pyplusplus_wrapper
