#ifndef AbstractSimplePhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
#define AbstractSimplePhaseBasedCellCycleModel_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractSimplePhaseBasedCellCycleModel_class(py::module &m);
#endif // AbstractSimplePhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
