// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "AbstractSimpleCellCycleModel.pypp.hpp"

namespace bp = boost::python;

struct AbstractSimpleCellCycleModel_wrapper : AbstractSimpleCellCycleModel, bp::wrapper< AbstractSimpleCellCycleModel > {

    AbstractSimpleCellCycleModel_wrapper(::AbstractSimpleCellCycleModel const & rModel )
    : AbstractSimpleCellCycleModel( boost::ref(rModel) )
      , bp::wrapper< AbstractSimpleCellCycleModel >(){
        // copy constructor
    
    }

    AbstractSimpleCellCycleModel_wrapper( )
    : AbstractSimpleCellCycleModel( )
      , bp::wrapper< AbstractSimpleCellCycleModel >(){
        // null constructor
    
    }

    virtual void Initialise(  ) {
        if( bp::override func_Initialise = this->get_override( "Initialise" ) )
            func_Initialise(  );
        else{
            this->AbstractSimpleCellCycleModel::Initialise(  );
        }
    }
    
    void default_Initialise(  ) {
        AbstractSimpleCellCycleModel::Initialise( );
    }

    virtual void InitialiseDaughterCell(  ) {
        if( bp::override func_InitialiseDaughterCell = this->get_override( "InitialiseDaughterCell" ) )
            func_InitialiseDaughterCell(  );
        else{
            this->AbstractSimpleCellCycleModel::InitialiseDaughterCell(  );
        }
    }
    
    void default_InitialiseDaughterCell(  ) {
        AbstractSimpleCellCycleModel::InitialiseDaughterCell( );
    }

    virtual void OutputCellCycleModelParameters( ::out_stream & rParamsFile ){
        bp::override func_OutputCellCycleModelParameters = this->get_override( "OutputCellCycleModelParameters" );
        func_OutputCellCycleModelParameters( rParamsFile );
    }

    virtual bool ReadyToDivide(  ) {
        if( bp::override func_ReadyToDivide = this->get_override( "ReadyToDivide" ) )
            return func_ReadyToDivide(  );
        else{
            return this->AbstractSimpleCellCycleModel::ReadyToDivide(  );
        }
    }
    
    bool default_ReadyToDivide(  ) {
        return AbstractSimpleCellCycleModel::ReadyToDivide( );
    }

    virtual void ResetForDivision(  ) {
        if( bp::override func_ResetForDivision = this->get_override( "ResetForDivision" ) )
            func_ResetForDivision(  );
        else{
            this->AbstractSimpleCellCycleModel::ResetForDivision(  );
        }
    }
    
    void default_ResetForDivision(  ) {
        AbstractSimpleCellCycleModel::ResetForDivision( );
    }

    virtual void SetCellCycleDuration(  ){
        bp::override func_SetCellCycleDuration = this->get_override( "SetCellCycleDuration" );
        func_SetCellCycleDuration(  );
    }

    virtual bool CanCellTerminallyDifferentiate(  ) {
        if( bp::override func_CanCellTerminallyDifferentiate = this->get_override( "CanCellTerminallyDifferentiate" ) )
            return func_CanCellTerminallyDifferentiate(  );
        else{
            return this->AbstractCellCycleModel::CanCellTerminallyDifferentiate(  );
        }
    }
    
    bool default_CanCellTerminallyDifferentiate(  ) {
        return AbstractCellCycleModel::CanCellTerminallyDifferentiate( );
    }

    virtual ::AbstractCellCycleModel * CreateCellCycleModel(  ){
        bp::override func_CreateCellCycleModel = this->get_override( "CreateCellCycleModel" );
        return func_CreateCellCycleModel(  );
    }

    virtual double GetAverageStemCellCycleTime(  ){
        bp::override func_GetAverageStemCellCycleTime = this->get_override( "GetAverageStemCellCycleTime" );
        return func_GetAverageStemCellCycleTime(  );
    }

    virtual double GetAverageTransitCellCycleTime(  ){
        bp::override func_GetAverageTransitCellCycleTime = this->get_override( "GetAverageTransitCellCycleTime" );
        return func_GetAverageTransitCellCycleTime(  );
    }

    virtual void SetBirthTime( double birthTime ) {
        if( bp::override func_SetBirthTime = this->get_override( "SetBirthTime" ) )
            func_SetBirthTime( birthTime );
        else{
            this->AbstractCellCycleModel::SetBirthTime( birthTime );
        }
    }
    
    void default_SetBirthTime( double birthTime ) {
        AbstractCellCycleModel::SetBirthTime( birthTime );
    }

};

void register_AbstractSimpleCellCycleModel_class(){

    bp::class_< AbstractSimpleCellCycleModel_wrapper, bp::bases< AbstractCellCycleModel >, boost::noncopyable >( "AbstractSimpleCellCycleModel", bp::init< AbstractSimpleCellCycleModel const & >(( bp::arg("rModel") )) )    
        .def( bp::init< >() )    
        .def( 
            "GetCellCycleDuration"
            , (double ( ::AbstractSimpleCellCycleModel::* )(  )const)( &::AbstractSimpleCellCycleModel::GetCellCycleDuration ) )    
        .def( 
            "Initialise"
            , (void ( ::AbstractSimpleCellCycleModel::* )(  ))(&::AbstractSimpleCellCycleModel::Initialise)
            , (void ( AbstractSimpleCellCycleModel_wrapper::* )(  ))(&AbstractSimpleCellCycleModel_wrapper::default_Initialise) )    
        .def( 
            "InitialiseDaughterCell"
            , (void ( ::AbstractSimpleCellCycleModel::* )(  ))(&::AbstractSimpleCellCycleModel::InitialiseDaughterCell)
            , (void ( AbstractSimpleCellCycleModel_wrapper::* )(  ))(&AbstractSimpleCellCycleModel_wrapper::default_InitialiseDaughterCell) )    
        .def( 
            "OutputCellCycleModelParameters"
            , bp::pure_virtual( (void ( ::AbstractSimpleCellCycleModel::* )( ::out_stream & ))(&::AbstractSimpleCellCycleModel::OutputCellCycleModelParameters) )
            , ( bp::arg("rParamsFile") ) )    
        .def( 
            "ReadyToDivide"
            , (bool ( ::AbstractSimpleCellCycleModel::* )(  ))(&::AbstractSimpleCellCycleModel::ReadyToDivide)
            , (bool ( AbstractSimpleCellCycleModel_wrapper::* )(  ))(&AbstractSimpleCellCycleModel_wrapper::default_ReadyToDivide) )    
        .def( 
            "ResetForDivision"
            , (void ( ::AbstractSimpleCellCycleModel::* )(  ))(&::AbstractSimpleCellCycleModel::ResetForDivision)
            , (void ( AbstractSimpleCellCycleModel_wrapper::* )(  ))(&AbstractSimpleCellCycleModel_wrapper::default_ResetForDivision) )    
        .def( 
            "SetCellCycleDuration"
            , bp::pure_virtual( (void ( ::AbstractSimpleCellCycleModel::* )(  ))(&::AbstractSimpleCellCycleModel::SetCellCycleDuration) ) )    
        .def( 
            "CanCellTerminallyDifferentiate"
            , (bool ( ::AbstractCellCycleModel::* )(  ))(&::AbstractCellCycleModel::CanCellTerminallyDifferentiate)
            , (bool ( AbstractSimpleCellCycleModel_wrapper::* )(  ))(&AbstractSimpleCellCycleModel_wrapper::default_CanCellTerminallyDifferentiate) )    
        .def( 
            "CreateCellCycleModel"
            , bp::pure_virtual( (::AbstractCellCycleModel * ( ::AbstractCellCycleModel::* )(  ))(&::AbstractCellCycleModel::CreateCellCycleModel) )
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "GetAverageStemCellCycleTime"
            , bp::pure_virtual( (double ( ::AbstractCellCycleModel::* )(  ))(&::AbstractCellCycleModel::GetAverageStemCellCycleTime) ) )    
        .def( 
            "GetAverageTransitCellCycleTime"
            , bp::pure_virtual( (double ( ::AbstractCellCycleModel::* )(  ))(&::AbstractCellCycleModel::GetAverageTransitCellCycleTime) ) )    
        .def( 
            "SetBirthTime"
            , (void ( ::AbstractCellCycleModel::* )( double ))(&::AbstractCellCycleModel::SetBirthTime)
            , (void ( AbstractSimpleCellCycleModel_wrapper::* )( double ))(&AbstractSimpleCellCycleModel_wrapper::default_SetBirthTime)
            , ( bp::arg("birthTime") ) );

}
