#ifndef AbstractPhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
#define AbstractPhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractPhaseBasedCellCycleModel_class(py::module &m);
#endif // AbstractPhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
