namespace py = pybind11;

#ifndef AbstractVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
#define AbstractVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
void register_AbstractVertexBasedDivisionRule2_class(py::module &m);
#endif // AbstractVertexBasedDivisionRule2_hpp__pyplusplus_wrapper
