namespace py = pybind11;

#ifndef AbstractOnLatticeCellPopulation3_hpp__pyplusplus_wrapper
#define AbstractOnLatticeCellPopulation3_hpp__pyplusplus_wrapper
void register_AbstractOnLatticeCellPopulation3_class(py::module &m);
#endif // AbstractOnLatticeCellPopulation3_hpp__pyplusplus_wrapper
