// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "AbstractCellBasedSimulation3_3.pypp.hpp"

namespace bp = boost::python;

struct AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper : AbstractCellBasedSimulation< 3, 3 >, bp::wrapper< AbstractCellBasedSimulation< 3, 3 > > {

    AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper(::AbstractCellPopulation< 3, 3 > & rCellPopulation, bool deleteCellPopulationInDestructor=false, bool initialiseCells=true )
    : AbstractCellBasedSimulation<3, 3>( boost::ref(rCellPopulation), deleteCellPopulationInDestructor, initialiseCells )
      , bp::wrapper< AbstractCellBasedSimulation< 3, 3 > >(){
        // constructor
    
    }

    virtual unsigned int DoCellBirth(  ){
        if( bp::override func_DoCellBirth = this->get_override( "DoCellBirth" ) )
            return func_DoCellBirth(  );
        else{
            return this->AbstractCellBasedSimulation< 3, 3 >::DoCellBirth(  );
        }
    }
    
    virtual unsigned int default_DoCellBirth(  ){
        return AbstractCellBasedSimulation< 3, 3 >::DoCellBirth( );
    }

    unsigned int DoCellRemoval(  ){
        return AbstractCellBasedSimulation< 3, 3 >::DoCellRemoval(  );
    }

    virtual void OutputAdditionalSimulationSetup( ::out_stream & rParamsFile ){
        bp::override func_OutputAdditionalSimulationSetup = this->get_override( "OutputAdditionalSimulationSetup" );
        func_OutputAdditionalSimulationSetup( rParamsFile );
    }

    virtual void OutputSimulationParameters( ::out_stream & rParamsFile ){
        bp::override func_OutputSimulationParameters = this->get_override( "OutputSimulationParameters" );
        func_OutputSimulationParameters( rParamsFile );
    }

    void OutputSimulationSetup(  ){
        AbstractCellBasedSimulation< 3, 3 >::OutputSimulationSetup(  );
    }

    virtual void SetupSolve(  ){
        if( bp::override func_SetupSolve = this->get_override( "SetupSolve" ) )
            func_SetupSolve(  );
        else{
            this->AbstractCellBasedSimulation< 3, 3 >::SetupSolve(  );
        }
    }
    
    virtual void default_SetupSolve(  ){
        AbstractCellBasedSimulation< 3, 3 >::SetupSolve( );
    }

    virtual bool StoppingEventHasOccurred(  ){
        if( bp::override func_StoppingEventHasOccurred = this->get_override( "StoppingEventHasOccurred" ) )
            return func_StoppingEventHasOccurred(  );
        else{
            return this->AbstractCellBasedSimulation< 3, 3 >::StoppingEventHasOccurred(  );
        }
    }
    
    virtual bool default_StoppingEventHasOccurred(  ){
        return AbstractCellBasedSimulation< 3, 3 >::StoppingEventHasOccurred( );
    }

    virtual void UpdateCellLocationsAndTopology(  ){
        bp::override func_UpdateCellLocationsAndTopology = this->get_override( "UpdateCellLocationsAndTopology" );
        func_UpdateCellLocationsAndTopology(  );
    }

    virtual void UpdateCellPopulation(  ){
        if( bp::override func_UpdateCellPopulation = this->get_override( "UpdateCellPopulation" ) )
            func_UpdateCellPopulation(  );
        else{
            this->AbstractCellBasedSimulation< 3, 3 >::UpdateCellPopulation(  );
        }
    }
    
    virtual void default_UpdateCellPopulation(  ){
        AbstractCellBasedSimulation< 3, 3 >::UpdateCellPopulation( );
    }

    virtual void WriteVisualizerSetupFile(  ){
        if( bp::override func_WriteVisualizerSetupFile = this->get_override( "WriteVisualizerSetupFile" ) )
            func_WriteVisualizerSetupFile(  );
        else{
            this->AbstractCellBasedSimulation< 3, 3 >::WriteVisualizerSetupFile(  );
        }
    }
    
    virtual void default_WriteVisualizerSetupFile(  ){
        AbstractCellBasedSimulation< 3, 3 >::WriteVisualizerSetupFile( );
    }

};

void register_AbstractCellBasedSimulation3_3_class(){

    bp::class_< AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper, boost::noncopyable >( "AbstractCellBasedSimulation3_3", bp::init< AbstractCellPopulation< 3, 3 > &, bp::optional< bool, bool > >(( bp::arg("rCellPopulation"), bp::arg("deleteCellPopulationInDestructor")=(bool)(false), bp::arg("initialiseCells")=(bool)(true) )) )    
        .def( 
            "AddCellKiller"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( ::boost::shared_ptr< AbstractCellKiller< 3 > > ))( &::AbstractCellBasedSimulation< 3, 3 >::AddCellKiller )
            , ( bp::arg("pCellKiller") ) )    
        .def( 
            "AddSimulationModifier"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( ::boost::shared_ptr< AbstractCellBasedSimulationModifier< 3, 3 > > ))( &::AbstractCellBasedSimulation< 3, 3 >::AddSimulationModifier )
            , ( bp::arg("pSimulationModifier") ) )    
        .def( 
            "DoCellBirth"
            , (unsigned int ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::default_DoCellBirth) )    
        .def( 
            "DoCellRemoval"
            , (unsigned int ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::DoCellRemoval) )    
        .def( 
            "GetDt"
            , (double ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::GetDt ) )    
        .def( 
            "GetNodeLocation"
            , (::std::vector< double > ( ::AbstractCellBasedSimulation<3, 3>::* )( unsigned int const & ))( &::AbstractCellBasedSimulation< 3, 3 >::GetNodeLocation )
            , ( bp::arg("rNodeIndex") ) )    
        .def( 
            "GetNumBirths"
            , (unsigned int ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::GetNumBirths ) )    
        .def( 
            "GetNumDeaths"
            , (unsigned int ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::GetNumDeaths ) )    
        .def( 
            "GetOutputCellVelocities"
            , (bool ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::GetOutputCellVelocities ) )    
        .def( 
            "GetOutputDirectory"
            , (::std::string ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::GetOutputDirectory ) )    
        .def( 
            "GetOutputDivisionLocations"
            , (bool ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::GetOutputDivisionLocations ) )    
        .def( 
            "GetUpdateCellPopulationRule"
            , (bool ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::GetUpdateCellPopulationRule ) )    
        .def( 
            "OutputAdditionalSimulationSetup"
            , (void ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )( ::out_stream & ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::OutputAdditionalSimulationSetup)
            , ( bp::arg("rParamsFile") ) )    
        .def( 
            "OutputSimulationParameters"
            , bp::pure_virtual( (void ( ::AbstractCellBasedSimulation<3, 3>::* )( ::out_stream & ))(&::AbstractCellBasedSimulation< 3, 3 >::OutputSimulationParameters) )
            , ( bp::arg("rParamsFile") ) )    
        .def( 
            "OutputSimulationSetup"
            , (void ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::OutputSimulationSetup) )    
        .def( 
            "RemoveAllCellKillers"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::RemoveAllCellKillers ) )    
        .def( 
            "SetDt"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( double ))( &::AbstractCellBasedSimulation< 3, 3 >::SetDt )
            , ( bp::arg("dt") ) )    
        .def( 
            "SetEndTime"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( double ))( &::AbstractCellBasedSimulation< 3, 3 >::SetEndTime )
            , ( bp::arg("endTime") ) )    
        .def( 
            "SetNoBirth"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( bool ))( &::AbstractCellBasedSimulation< 3, 3 >::SetNoBirth )
            , ( bp::arg("noBirth") ) )    
        .def( 
            "SetOutputCellVelocities"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( bool ))( &::AbstractCellBasedSimulation< 3, 3 >::SetOutputCellVelocities )
            , ( bp::arg("outputCellVelocities") ) )    
        .def( 
            "SetOutputDirectory"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( ::std::string ))( &::AbstractCellBasedSimulation< 3, 3 >::SetOutputDirectory )
            , ( bp::arg("outputDirectory") ) )    
        .def( 
            "SetOutputDivisionLocations"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( bool ))( &::AbstractCellBasedSimulation< 3, 3 >::SetOutputDivisionLocations )
            , ( bp::arg("outputDivisionLocations") ) )    
        .def( 
            "SetSamplingTimestepMultiple"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( unsigned int ))( &::AbstractCellBasedSimulation< 3, 3 >::SetSamplingTimestepMultiple )
            , ( bp::arg("samplingTimestepMultiple") ) )    
        .def( 
            "SetUpdateCellPopulationRule"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )( bool ))( &::AbstractCellBasedSimulation< 3, 3 >::SetUpdateCellPopulationRule )
            , ( bp::arg("updateCellPopulation") ) )    
        .def( 
            "SetupSolve"
            , (void ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::default_SetupSolve) )    
        .def( 
            "Solve"
            , (void ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::Solve ) )    
        .def( 
            "StoppingEventHasOccurred"
            , (bool ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::default_StoppingEventHasOccurred) )    
        .def( 
            "UpdateCellLocationsAndTopology"
            , (void ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::UpdateCellLocationsAndTopology) )    
        .def( 
            "UpdateCellPopulation"
            , (void ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::default_UpdateCellPopulation) )    
        .def( 
            "WriteVisualizerSetupFile"
            , (void ( AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractCellBasedSimulation_less__3_comma__3__greater__wrapper::default_WriteVisualizerSetupFile) )    
        .def( 
            "rGetCellPopulation"
            , (::AbstractCellPopulation< 3, 3 > & ( ::AbstractCellBasedSimulation<3, 3>::* )(  ))( &::AbstractCellBasedSimulation< 3, 3 >::rGetCellPopulation )
            , bp::return_internal_reference< >() )    
        .def( 
            "rGetCellPopulation"
            , (::AbstractCellPopulation< 3, 3 > const & ( ::AbstractCellBasedSimulation<3, 3>::* )(  )const)( &::AbstractCellBasedSimulation< 3, 3 >::rGetCellPopulation )
            , bp::return_internal_reference< >() );

}
