namespace py = pybind11;

#ifndef AbstractTwoBodyInteractionForce3_3_hpp__pyplusplus_wrapper
#define AbstractTwoBodyInteractionForce3_3_hpp__pyplusplus_wrapper
void register_AbstractTwoBodyInteractionForce3_3_class(py::module &m);
#endif // AbstractTwoBodyInteractionForce3_3_hpp__pyplusplus_wrapper
