namespace py = pybind11;

#ifndef AbstractCentreBasedCellPopulation3_3_hpp__pyplusplus_wrapper
#define AbstractCentreBasedCellPopulation3_3_hpp__pyplusplus_wrapper
void register_AbstractCentreBasedCellPopulation3_3_class(py::module &m);
#endif // AbstractCentreBasedCellPopulation3_3_hpp__pyplusplus_wrapper
