namespace py = pybind11;

#ifndef AbstractTwoBodyInteractionForce2_2_hpp__pyplusplus_wrapper
#define AbstractTwoBodyInteractionForce2_2_hpp__pyplusplus_wrapper
void register_AbstractTwoBodyInteractionForce2_2_class(py::module &m);
#endif // AbstractTwoBodyInteractionForce2_2_hpp__pyplusplus_wrapper
