namespace py = pybind11;

#ifndef AbstractCellPopulationBoundaryCondition2_2_hpp__pyplusplus_wrapper
#define AbstractCellPopulationBoundaryCondition2_2_hpp__pyplusplus_wrapper
void register_AbstractCellPopulationBoundaryCondition2_2_class(py::module &m);
#endif // AbstractCellPopulationBoundaryCondition2_2_hpp__pyplusplus_wrapper
