#ifndef AbstractGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
#define AbstractGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractGrowingDomainPdeModifier3_class(py::module &m);
#endif // AbstractGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
