#ifndef AbstractLinearEllipticPde2_2_hpp__pyplusplus_wrapper
#define AbstractLinearEllipticPde2_2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractLinearEllipticPde2_2_class(py::module &m);
#endif // AbstractLinearEllipticPde2_2_hpp__pyplusplus_wrapper
