// This file has been generated by Py++.


/*

Copyright (c) 2005-2016, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "cell_based_headers.hpp"
#include "AbstractCellPopulationBoundaryCondition3_3.pypp.hpp"

namespace bp = boost::python;

struct AbstractCellPopulationBoundaryCondition_less__3_comma__3__greater__wrapper : AbstractCellPopulationBoundaryCondition< 3, 3 >, bp::wrapper< AbstractCellPopulationBoundaryCondition< 3, 3 > > {

    AbstractCellPopulationBoundaryCondition_less__3_comma__3__greater__wrapper(::AbstractCellPopulation< 3, 3 > * pCellPopulation )
    : AbstractCellPopulationBoundaryCondition<3, 3>( boost::python::ptr(pCellPopulation) )
      , bp::wrapper< AbstractCellPopulationBoundaryCondition< 3, 3 > >(){
        // constructor
    
    }

    virtual void ImposeBoundaryCondition( ::std::map< Node<3> *, boost::numeric::ublas::c_vector<double, 3> > const & rOldLocations ){
        bp::override func_ImposeBoundaryCondition = this->get_override( "ImposeBoundaryCondition" );
        func_ImposeBoundaryCondition( boost::ref(rOldLocations) );
    }

    virtual void OutputCellPopulationBoundaryConditionParameters( ::out_stream & rParamsFile ){
        bp::override func_OutputCellPopulationBoundaryConditionParameters = this->get_override( "OutputCellPopulationBoundaryConditionParameters" );
        func_OutputCellPopulationBoundaryConditionParameters( boost::ref(rParamsFile) );
    }

    virtual bool VerifyBoundaryCondition(  ){
        bp::override func_VerifyBoundaryCondition = this->get_override( "VerifyBoundaryCondition" );
        return func_VerifyBoundaryCondition(  );
    }

};

void register_AbstractCellPopulationBoundaryCondition3_3_class(){

    { //::AbstractCellPopulationBoundaryCondition< 3, 3 >
        typedef bp::class_< AbstractCellPopulationBoundaryCondition_less__3_comma__3__greater__wrapper, bp::bases< Identifiable >, boost::noncopyable > AbstractCellPopulationBoundaryCondition3_3_exposer_t;
        AbstractCellPopulationBoundaryCondition3_3_exposer_t AbstractCellPopulationBoundaryCondition3_3_exposer = AbstractCellPopulationBoundaryCondition3_3_exposer_t( "AbstractCellPopulationBoundaryCondition3_3", bp::init< AbstractCellPopulation< 3, 3 > * >(( bp::arg("pCellPopulation") )) );
        bp::scope AbstractCellPopulationBoundaryCondition3_3_scope( AbstractCellPopulationBoundaryCondition3_3_exposer );
        { //::AbstractCellPopulationBoundaryCondition< 3, 3 >::GetCellPopulation
        
            typedef AbstractCellPopulationBoundaryCondition< 3, 3 > exported_class_t;
            typedef ::AbstractCellPopulation< 3, 3 > const * ( exported_class_t::*GetCellPopulation_function_type)(  ) const;
            
            AbstractCellPopulationBoundaryCondition3_3_exposer.def( 
                "GetCellPopulation"
                , GetCellPopulation_function_type( &::AbstractCellPopulationBoundaryCondition< 3, 3 >::GetCellPopulation )
                , bp::return_value_policy< bp::manage_new_object >() );
        
        }
        { //::AbstractCellPopulationBoundaryCondition< 3, 3 >::ImposeBoundaryCondition
        
            typedef AbstractCellPopulationBoundaryCondition< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*ImposeBoundaryCondition_function_type)( ::std::map<Node<3> *, boost::numeric::ublas::c_vector<double, 3>, std::less<Node<3> *>, std::allocator<std::pair<Node<3> *const, boost::numeric::ublas::c_vector<double, 3> > > > const & ) ;
            
            AbstractCellPopulationBoundaryCondition3_3_exposer.def( 
                "ImposeBoundaryCondition"
                , bp::pure_virtual( ImposeBoundaryCondition_function_type(&::AbstractCellPopulationBoundaryCondition< 3, 3 >::ImposeBoundaryCondition) )
                , ( bp::arg("rOldLocations") ) );
        
        }
        { //::AbstractCellPopulationBoundaryCondition< 3, 3 >::OutputCellPopulationBoundaryConditionInfo
        
            typedef AbstractCellPopulationBoundaryCondition< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*OutputCellPopulationBoundaryConditionInfo_function_type)( ::out_stream & ) ;
            
            AbstractCellPopulationBoundaryCondition3_3_exposer.def( 
                "OutputCellPopulationBoundaryConditionInfo"
                , OutputCellPopulationBoundaryConditionInfo_function_type( &::AbstractCellPopulationBoundaryCondition< 3, 3 >::OutputCellPopulationBoundaryConditionInfo )
                , ( bp::arg("rParamsFile") ) );
        
        }
        { //::AbstractCellPopulationBoundaryCondition< 3, 3 >::OutputCellPopulationBoundaryConditionParameters
        
            typedef AbstractCellPopulationBoundaryCondition< 3, 3 > exported_class_t;
            typedef void ( exported_class_t::*OutputCellPopulationBoundaryConditionParameters_function_type)( ::out_stream & ) ;
            
            AbstractCellPopulationBoundaryCondition3_3_exposer.def( 
                "OutputCellPopulationBoundaryConditionParameters"
                , bp::pure_virtual( OutputCellPopulationBoundaryConditionParameters_function_type(&::AbstractCellPopulationBoundaryCondition< 3, 3 >::OutputCellPopulationBoundaryConditionParameters) )
                , ( bp::arg("rParamsFile") ) );
        
        }
        { //::AbstractCellPopulationBoundaryCondition< 3, 3 >::VerifyBoundaryCondition
        
            typedef AbstractCellPopulationBoundaryCondition< 3, 3 > exported_class_t;
            typedef bool ( exported_class_t::*VerifyBoundaryCondition_function_type)(  ) ;
            
            AbstractCellPopulationBoundaryCondition3_3_exposer.def( 
                "VerifyBoundaryCondition"
                , bp::pure_virtual( VerifyBoundaryCondition_function_type(&::AbstractCellPopulationBoundaryCondition< 3, 3 >::VerifyBoundaryCondition) ) );
        
        }
        bp::register_ptr_to_python< boost::shared_ptr< AbstractCellPopulationBoundaryCondition<3, 3> > >();
        bp::implicitly_convertible< boost::shared_ptr< AbstractCellPopulationBoundaryCondition< 3, 3 > >, boost::shared_ptr< Identifiable > >();
        bp::implicitly_convertible< boost::shared_ptr< AttractingPlaneBoundaryCondition< 3, 3 > >, boost::shared_ptr< AbstractCellPopulationBoundaryCondition< 3, 3 > > >();
        bp::implicitly_convertible< boost::shared_ptr< SphereGeometryBoundaryCondition< 3 > >, boost::shared_ptr< AbstractCellPopulationBoundaryCondition< 3, 3 > > >();
        bp::implicitly_convertible< boost::shared_ptr< PlaneBoundaryCondition< 3, 3 > >, boost::shared_ptr< AbstractCellPopulationBoundaryCondition< 3, 3 > > >();
    }

}
