namespace py = pybind11;

#ifndef AbstractGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
#define AbstractGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
void register_AbstractGrowingDomainPdeModifier3_class(py::module &m);
#endif // AbstractGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
