#ifndef AbstractTargetAreaModifier3_hpp__pyplusplus_wrapper
#define AbstractTargetAreaModifier3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractTargetAreaModifier3_class(py::module &m);
#endif // AbstractTargetAreaModifier3_hpp__pyplusplus_wrapper
