namespace py = pybind11;

#ifndef AbstractSimpleGenerationalCellCycleModel_hpp__pyplusplus_wrapper
#define AbstractSimpleGenerationalCellCycleModel_hpp__pyplusplus_wrapper
void register_AbstractSimpleGenerationalCellCycleModel_class(py::module &m);
#endif // AbstractSimpleGenerationalCellCycleModel_hpp__pyplusplus_wrapper
