#ifndef AbstractOffLatticeCellPopulation2_2_hpp__pyplusplus_wrapper
#define AbstractOffLatticeCellPopulation2_2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AbstractOffLatticeCellPopulation2_2_class(py::module &m);
#endif // AbstractOffLatticeCellPopulation2_2_hpp__pyplusplus_wrapper
