#ifndef AbstractCellPopulationBoundaryCondition2_2_hpp__pyplusplus_wrapper
#define AbstractCellPopulationBoundaryCondition2_2_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_AbstractCellPopulationBoundaryCondition2_2_class(py::module &m);
#endif // AbstractCellPopulationBoundaryCondition2_2_hpp__pyplusplus_wrapper
