namespace py = pybind11;

#ifndef AbstractVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
#define AbstractVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
void register_AbstractVertexBasedDivisionRule3_class(py::module &m);
#endif // AbstractVertexBasedDivisionRule3_hpp__pyplusplus_wrapper
