namespace py = pybind11;

#ifndef AbstractCellBasedSimulation2_2_hpp__pyplusplus_wrapper
#define AbstractCellBasedSimulation2_2_hpp__pyplusplus_wrapper
void register_AbstractCellBasedSimulation2_2_class(py::module &m);
#endif // AbstractCellBasedSimulation2_2_hpp__pyplusplus_wrapper
