namespace py = pybind11;

#ifndef AbstractSimplePhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
#define AbstractSimplePhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
void register_AbstractSimplePhaseBasedCellCycleModel_class(py::module &m);
#endif // AbstractSimplePhaseBasedCellCycleModel_hpp__pyplusplus_wrapper
