namespace py = pybind11;

#ifndef AttractingPlaneBoundaryCondition3_3_hpp__pyplusplus_wrapper
#define AttractingPlaneBoundaryCondition3_3_hpp__pyplusplus_wrapper
void register_AttractingPlaneBoundaryCondition3_3_class(py::module &m);
#endif // AttractingPlaneBoundaryCondition3_3_hpp__pyplusplus_wrapper
