namespace py = pybind11;

#ifndef AttractingPlaneBoundaryCondition2_2_hpp__pyplusplus_wrapper
#define AttractingPlaneBoundaryCondition2_2_hpp__pyplusplus_wrapper
void register_AttractingPlaneBoundaryCondition2_2_class(py::module &m);
#endif // AttractingPlaneBoundaryCondition2_2_hpp__pyplusplus_wrapper
