#ifndef AveragedSourceParabolicPde2_hpp__pyplusplus_wrapper
#define AveragedSourceParabolicPde2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AveragedSourceParabolicPde2_class(py::module &m);
#endif // AveragedSourceParabolicPde2_hpp__pyplusplus_wrapper
