#ifndef AveragedSourceParabolicPde3_hpp__pyplusplus_wrapper
#define AveragedSourceParabolicPde3_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_AveragedSourceParabolicPde3_class(py::module &m);
#endif // AveragedSourceParabolicPde3_hpp__pyplusplus_wrapper
