// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "CaBasedCellPopulation3.pypp.hpp"

namespace bp = boost::python;

struct CaBasedCellPopulation_less__3__greater__wrapper : CaBasedCellPopulation< 3 >, bp::wrapper< CaBasedCellPopulation< 3 > > {

    CaBasedCellPopulation_less__3__greater__wrapper(::PottsMesh< 3 > & rMesh, ::std::vector< boost::shared_ptr<Cell> > & rCells, ::std::vector< unsigned int > const locationIndices, unsigned int latticeCarryingCapacity=1U, bool deleteMesh=false, bool validate=false )
    : CaBasedCellPopulation<3>( boost::ref(rMesh), boost::ref(rCells), locationIndices, latticeCarryingCapacity, deleteMesh, validate )
      , bp::wrapper< CaBasedCellPopulation< 3 > >(){
        // constructor
    
    }

    CaBasedCellPopulation_less__3__greater__wrapper(::PottsMesh< 3 > & rMesh )
    : CaBasedCellPopulation<3>( boost::ref(rMesh) )
      , bp::wrapper< CaBasedCellPopulation< 3 > >(){
        // constructor
    
    }

    virtual void AcceptCellWriter( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > > pCellWriter, ::CellPtr pCell ) {
        if( bp::override func_AcceptCellWriter = this->get_override( "AcceptCellWriter" ) )
            func_AcceptCellWriter( pCellWriter, pCell );
        else{
            this->CaBasedCellPopulation< 3 >::AcceptCellWriter( pCellWriter, pCell );
        }
    }
    
    void default_AcceptCellWriter( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > > pCellWriter, ::CellPtr pCell ) {
        CaBasedCellPopulation< 3 >::AcceptCellWriter( pCellWriter, pCell );
    }

    virtual void AcceptPopulationCountWriter( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > pPopulationCountWriter ) {
        if( bp::override func_AcceptPopulationCountWriter = this->get_override( "AcceptPopulationCountWriter" ) )
            func_AcceptPopulationCountWriter( pPopulationCountWriter );
        else{
            this->CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter( pPopulationCountWriter );
        }
    }
    
    void default_AcceptPopulationCountWriter( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > pPopulationCountWriter ) {
        CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter( pPopulationCountWriter );
    }

    virtual void AcceptPopulationWriter( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > pPopulationWriter ) {
        if( bp::override func_AcceptPopulationWriter = this->get_override( "AcceptPopulationWriter" ) )
            func_AcceptPopulationWriter( pPopulationWriter );
        else{
            this->CaBasedCellPopulation< 3 >::AcceptPopulationWriter( pPopulationWriter );
        }
    }
    
    void default_AcceptPopulationWriter( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > pPopulationWriter ) {
        CaBasedCellPopulation< 3 >::AcceptPopulationWriter( pPopulationWriter );
    }

    virtual ::CellPtr AddCell( ::CellPtr pNewCell, ::CellPtr pParentCell=::CellPtr( ) ) {
        if( bp::override func_AddCell = this->get_override( "AddCell" ) )
            return func_AddCell( pNewCell, pParentCell );
        else{
            return this->CaBasedCellPopulation< 3 >::AddCell( pNewCell, pParentCell );
        }
    }
    
    ::CellPtr default_AddCell( ::CellPtr pNewCell, ::CellPtr pParentCell=::CellPtr( ) ) {
        return CaBasedCellPopulation< 3 >::AddCell( pNewCell, pParentCell );
    }

    virtual void AddCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        if( bp::override func_AddCellUsingLocationIndex = this->get_override( "AddCellUsingLocationIndex" ) )
            func_AddCellUsingLocationIndex( index, pCell );
        else{
            this->CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex( index, pCell );
        }
    }
    
    void default_AddCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex( index, pCell );
    }

    virtual void AddUpdateRule( ::boost::shared_ptr< AbstractUpdateRule< 3 > > pUpdateRule ) {
        if( bp::override func_AddUpdateRule = this->get_override( "AddUpdateRule" ) )
            func_AddUpdateRule( pUpdateRule );
        else{
            this->CaBasedCellPopulation< 3 >::AddUpdateRule( pUpdateRule );
        }
    }
    
    void default_AddUpdateRule( ::boost::shared_ptr< AbstractUpdateRule< 3 > > pUpdateRule ) {
        CaBasedCellPopulation< 3 >::AddUpdateRule( pUpdateRule );
    }

    virtual double EvaluateDivisionPropensity( unsigned int currentNodeIndex, unsigned int targetNodeIndex, ::CellPtr pCell ) {
        if( bp::override func_EvaluateDivisionPropensity = this->get_override( "EvaluateDivisionPropensity" ) )
            return func_EvaluateDivisionPropensity( currentNodeIndex, targetNodeIndex, pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity( currentNodeIndex, targetNodeIndex, pCell );
        }
    }
    
    double default_EvaluateDivisionPropensity( unsigned int currentNodeIndex, unsigned int targetNodeIndex, ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity( currentNodeIndex, targetNodeIndex, pCell );
    }

    virtual double GetCellDataItemAtPdeNode( unsigned int pdeNodeIndex, ::std::string & rVariableName, bool dirichletBoundaryConditionApplies=false, double dirichletBoundaryValue=0. ) {
        if( bp::override func_GetCellDataItemAtPdeNode = this->get_override( "GetCellDataItemAtPdeNode" ) )
            return func_GetCellDataItemAtPdeNode( pdeNodeIndex, rVariableName, dirichletBoundaryConditionApplies, dirichletBoundaryValue );
        else{
            return this->CaBasedCellPopulation< 3 >::GetCellDataItemAtPdeNode( pdeNodeIndex, rVariableName, dirichletBoundaryConditionApplies, dirichletBoundaryValue );
        }
    }
    
    double default_GetCellDataItemAtPdeNode( unsigned int pdeNodeIndex, ::std::string & rVariableName, bool dirichletBoundaryConditionApplies=false, double dirichletBoundaryValue=0. ) {
        return CaBasedCellPopulation< 3 >::GetCellDataItemAtPdeNode( pdeNodeIndex, rVariableName, dirichletBoundaryConditionApplies, dirichletBoundaryValue );
    }

    virtual ::boost::numeric::ublas::c_vector< double, 3 > GetLocationOfCellCentre( ::CellPtr pCell ) {
        if( bp::override func_GetLocationOfCellCentre = this->get_override( "GetLocationOfCellCentre" ) )
            return func_GetLocationOfCellCentre( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::GetLocationOfCellCentre( pCell );
        }
    }
    
    ::boost::numeric::ublas::c_vector< double, 3 > default_GetLocationOfCellCentre( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::GetLocationOfCellCentre( pCell );
    }

    virtual ::std::set< unsigned int > GetNeighbouringLocationIndices( ::CellPtr pCell ) {
        if( bp::override func_GetNeighbouringLocationIndices = this->get_override( "GetNeighbouringLocationIndices" ) )
            return func_GetNeighbouringLocationIndices( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices( pCell );
        }
    }
    
    ::std::set< unsigned int > default_GetNeighbouringLocationIndices( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices( pCell );
    }

    virtual ::Node< 3 > * GetNode( unsigned int index ) {
        if( bp::override func_GetNode = this->get_override( "GetNode" ) )
            return func_GetNode( index );
        else{
            return this->CaBasedCellPopulation< 3 >::GetNode( index );
        }
    }
    
    ::Node< 3 > * default_GetNode( unsigned int index ) {
        return CaBasedCellPopulation< 3 >::GetNode( index );
    }

    virtual unsigned int GetNumNodes(  ) {
        if( bp::override func_GetNumNodes = this->get_override( "GetNumNodes" ) )
            return func_GetNumNodes(  );
        else{
            return this->CaBasedCellPopulation< 3 >::GetNumNodes(  );
        }
    }
    
    unsigned int default_GetNumNodes(  ) {
        return CaBasedCellPopulation< 3 >::GetNumNodes( );
    }

    virtual ::TetrahedralMesh< 3, 3 > * GetTetrahedralMeshForPdeModifier(  ) {
        if( bp::override func_GetTetrahedralMeshForPdeModifier = this->get_override( "GetTetrahedralMeshForPdeModifier" ) )
            return func_GetTetrahedralMeshForPdeModifier(  );
        else{
            return this->CaBasedCellPopulation< 3 >::GetTetrahedralMeshForPdeModifier(  );
        }
    }
    
    ::TetrahedralMesh< 3, 3 > * default_GetTetrahedralMeshForPdeModifier(  ) {
        return CaBasedCellPopulation< 3 >::GetTetrahedralMeshForPdeModifier( );
    }

    virtual ::std::vector< boost::shared_ptr<AbstractUpdateRule<3> > > const GetUpdateRuleCollection(  ) const  {
        if( bp::override func_GetUpdateRuleCollection = this->get_override( "GetUpdateRuleCollection" ) )
            return func_GetUpdateRuleCollection(  );
        else{
            return this->CaBasedCellPopulation< 3 >::GetUpdateRuleCollection(  );
        }
    }
    
    ::std::vector< boost::shared_ptr<AbstractUpdateRule<3> > > const default_GetUpdateRuleCollection(  ) const  {
        return CaBasedCellPopulation< 3 >::GetUpdateRuleCollection( );
    }

    virtual double GetVolumeOfCell( ::CellPtr pCell ) {
        if( bp::override func_GetVolumeOfCell = this->get_override( "GetVolumeOfCell" ) )
            return func_GetVolumeOfCell( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::GetVolumeOfCell( pCell );
        }
    }
    
    double default_GetVolumeOfCell( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::GetVolumeOfCell( pCell );
    }

    virtual double GetWidth( unsigned int const & rDimension ) {
        if( bp::override func_GetWidth = this->get_override( "GetWidth" ) )
            return func_GetWidth( rDimension );
        else{
            return this->CaBasedCellPopulation< 3 >::GetWidth( rDimension );
        }
    }
    
    double default_GetWidth( unsigned int const & rDimension ) {
        return CaBasedCellPopulation< 3 >::GetWidth( rDimension );
    }

    virtual bool IsCellAssociatedWithADeletedLocation( ::CellPtr pCell ) {
        if( bp::override func_IsCellAssociatedWithADeletedLocation = this->get_override( "IsCellAssociatedWithADeletedLocation" ) )
            return func_IsCellAssociatedWithADeletedLocation( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation( pCell );
        }
    }
    
    bool default_IsCellAssociatedWithADeletedLocation( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation( pCell );
    }

    virtual bool IsPdeNodeAssociatedWithNonApoptoticCell( unsigned int pdeNodeIndex ) {
        if( bp::override func_IsPdeNodeAssociatedWithNonApoptoticCell = this->get_override( "IsPdeNodeAssociatedWithNonApoptoticCell" ) )
            return func_IsPdeNodeAssociatedWithNonApoptoticCell( pdeNodeIndex );
        else{
            return this->CaBasedCellPopulation< 3 >::IsPdeNodeAssociatedWithNonApoptoticCell( pdeNodeIndex );
        }
    }
    
    bool default_IsPdeNodeAssociatedWithNonApoptoticCell( unsigned int pdeNodeIndex ) {
        return CaBasedCellPopulation< 3 >::IsPdeNodeAssociatedWithNonApoptoticCell( pdeNodeIndex );
    }

    virtual bool IsRoomToDivide( ::CellPtr pCell ) {
        if( bp::override func_IsRoomToDivide = this->get_override( "IsRoomToDivide" ) )
            return func_IsRoomToDivide( pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::IsRoomToDivide( pCell );
        }
    }
    
    bool default_IsRoomToDivide( ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::IsRoomToDivide( pCell );
    }

    virtual bool IsSiteAvailable( unsigned int index, ::CellPtr pCell ) {
        if( bp::override func_IsSiteAvailable = this->get_override( "IsSiteAvailable" ) )
            return func_IsSiteAvailable( index, pCell );
        else{
            return this->CaBasedCellPopulation< 3 >::IsSiteAvailable( index, pCell );
        }
    }
    
    bool default_IsSiteAvailable( unsigned int index, ::CellPtr pCell ) {
        return CaBasedCellPopulation< 3 >::IsSiteAvailable( index, pCell );
    }

    virtual void OpenWritersFiles( ::OutputFileHandler & rOutputFileHandler ) {
        if( bp::override func_OpenWritersFiles = this->get_override( "OpenWritersFiles" ) )
            func_OpenWritersFiles( boost::ref(rOutputFileHandler) );
        else{
            this->CaBasedCellPopulation< 3 >::OpenWritersFiles( boost::ref(rOutputFileHandler) );
        }
    }
    
    void default_OpenWritersFiles( ::OutputFileHandler & rOutputFileHandler ) {
        CaBasedCellPopulation< 3 >::OpenWritersFiles( boost::ref(rOutputFileHandler) );
    }

    virtual void OutputCellPopulationParameters( ::out_stream & rParamsFile ) {
        if( bp::override func_OutputCellPopulationParameters = this->get_override( "OutputCellPopulationParameters" ) )
            func_OutputCellPopulationParameters( boost::ref(rParamsFile) );
        else{
            this->CaBasedCellPopulation< 3 >::OutputCellPopulationParameters( boost::ref(rParamsFile) );
        }
    }
    
    void default_OutputCellPopulationParameters( ::out_stream & rParamsFile ) {
        CaBasedCellPopulation< 3 >::OutputCellPopulationParameters( boost::ref(rParamsFile) );
    }

    virtual void RemoveAllUpdateRules(  ) {
        if( bp::override func_RemoveAllUpdateRules = this->get_override( "RemoveAllUpdateRules" ) )
            func_RemoveAllUpdateRules(  );
        else{
            this->CaBasedCellPopulation< 3 >::RemoveAllUpdateRules(  );
        }
    }
    
    void default_RemoveAllUpdateRules(  ) {
        CaBasedCellPopulation< 3 >::RemoveAllUpdateRules( );
    }

    virtual void RemoveCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        if( bp::override func_RemoveCellUsingLocationIndex = this->get_override( "RemoveCellUsingLocationIndex" ) )
            func_RemoveCellUsingLocationIndex( index, pCell );
        else{
            this->CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex( index, pCell );
        }
    }
    
    void default_RemoveCellUsingLocationIndex( unsigned int index, ::CellPtr pCell ) {
        CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex( index, pCell );
    }

    virtual unsigned int RemoveDeadCells(  ) {
        if( bp::override func_RemoveDeadCells = this->get_override( "RemoveDeadCells" ) )
            return func_RemoveDeadCells(  );
        else{
            return this->CaBasedCellPopulation< 3 >::RemoveDeadCells(  );
        }
    }
    
    unsigned int default_RemoveDeadCells(  ) {
        return CaBasedCellPopulation< 3 >::RemoveDeadCells( );
    }

    virtual void Update( bool hasHadBirthsOrDeaths=true ) {
        if( bp::override func_Update = this->get_override( "Update" ) )
            func_Update( hasHadBirthsOrDeaths );
        else{
            this->CaBasedCellPopulation< 3 >::Update( hasHadBirthsOrDeaths );
        }
    }
    
    void default_Update( bool hasHadBirthsOrDeaths=true ) {
        CaBasedCellPopulation< 3 >::Update( hasHadBirthsOrDeaths );
    }

    virtual void UpdateCellLocations( double dt ) {
        if( bp::override func_UpdateCellLocations = this->get_override( "UpdateCellLocations" ) )
            func_UpdateCellLocations( dt );
        else{
            this->CaBasedCellPopulation< 3 >::UpdateCellLocations( dt );
        }
    }
    
    void default_UpdateCellLocations( double dt ) {
        CaBasedCellPopulation< 3 >::UpdateCellLocations( dt );
    }

    virtual void AcceptCellWritersAcrossPopulation(  ){
        if( bp::override func_AcceptCellWritersAcrossPopulation = this->get_override( "AcceptCellWritersAcrossPopulation" ) )
            func_AcceptCellWritersAcrossPopulation(  );
        else{
            this->AbstractCellPopulation< 3, 3 >::AcceptCellWritersAcrossPopulation(  );
        }
    }
    
    virtual void default_AcceptCellWritersAcrossPopulation(  ){
        AbstractCellPopulation< 3, 3 >::AcceptCellWritersAcrossPopulation( );
    }

    virtual ::CellPtr GetCellUsingLocationIndex( unsigned int index ) {
        if( bp::override func_GetCellUsingLocationIndex = this->get_override( "GetCellUsingLocationIndex" ) )
            return func_GetCellUsingLocationIndex( index );
        else{
            return this->AbstractCellPopulation< 3, 3 >::GetCellUsingLocationIndex( index );
        }
    }
    
    ::CellPtr default_GetCellUsingLocationIndex( unsigned int index ) {
        return AbstractCellPopulation< 3, 3 >::GetCellUsingLocationIndex( index );
    }

    virtual double GetDefaultTimeStep(  ) {
        if( bp::override func_GetDefaultTimeStep = this->get_override( "GetDefaultTimeStep" ) )
            return func_GetDefaultTimeStep(  );
        else{
            return this->AbstractOnLatticeCellPopulation< 3 >::GetDefaultTimeStep(  );
        }
    }
    
    double default_GetDefaultTimeStep(  ) {
        return AbstractOnLatticeCellPopulation< 3 >::GetDefaultTimeStep( );
    }

    virtual ::std::set< unsigned int > GetNeighbouringNodeIndices( unsigned int index ) {
        if( bp::override func_GetNeighbouringNodeIndices = this->get_override( "GetNeighbouringNodeIndices" ) )
            return func_GetNeighbouringNodeIndices( index );
        else{
            return this->AbstractOnLatticeCellPopulation< 3 >::GetNeighbouringNodeIndices( index );
        }
    }
    
    ::std::set< unsigned int > default_GetNeighbouringNodeIndices( unsigned int index ) {
        return AbstractOnLatticeCellPopulation< 3 >::GetNeighbouringNodeIndices( index );
    }

    virtual bool IsCellAttachedToLocationIndex( unsigned int index ) {
        if( bp::override func_IsCellAttachedToLocationIndex = this->get_override( "IsCellAttachedToLocationIndex" ) )
            return func_IsCellAttachedToLocationIndex( index );
        else{
            return this->AbstractCellPopulation< 3, 3 >::IsCellAttachedToLocationIndex( index );
        }
    }
    
    bool default_IsCellAttachedToLocationIndex( unsigned int index ) {
        return AbstractCellPopulation< 3, 3 >::IsCellAttachedToLocationIndex( index );
    }

    virtual void SetNode( unsigned int index, ::ChastePoint< 3 > & rNewLocation ) {
        if( bp::override func_SetNode = this->get_override( "SetNode" ) )
            func_SetNode( index, boost::ref(rNewLocation) );
        else{
            this->AbstractOnLatticeCellPopulation< 3 >::SetNode( index, boost::ref(rNewLocation) );
        }
    }
    
    void default_SetNode( unsigned int index, ::ChastePoint< 3 > & rNewLocation ) {
        AbstractOnLatticeCellPopulation< 3 >::SetNode( index, boost::ref(rNewLocation) );
    }

    virtual void SimulationSetupHook( ::AbstractCellBasedSimulation< 3, 3 > * pSimulation ) {
        if( bp::override func_SimulationSetupHook = this->get_override( "SimulationSetupHook" ) )
            func_SimulationSetupHook( boost::python::ptr(pSimulation) );
        else{
            this->AbstractCellPopulation< 3, 3 >::SimulationSetupHook( boost::python::ptr(pSimulation) );
        }
    }
    
    void default_SimulationSetupHook( ::AbstractCellBasedSimulation< 3, 3 > * pSimulation ) {
        AbstractCellPopulation< 3, 3 >::SimulationSetupHook( boost::python::ptr(pSimulation) );
    }

    virtual void UpdateCellProcessLocation(  ) {
        if( bp::override func_UpdateCellProcessLocation = this->get_override( "UpdateCellProcessLocation" ) )
            func_UpdateCellProcessLocation(  );
        else{
            this->AbstractCellPopulation< 3, 3 >::UpdateCellProcessLocation(  );
        }
    }
    
    void default_UpdateCellProcessLocation(  ) {
        AbstractCellPopulation< 3, 3 >::UpdateCellProcessLocation( );
    }

    virtual void WriteDataToVisualizerSetupFile( ::out_stream & pVizSetupFile ) {
        if( bp::override func_WriteDataToVisualizerSetupFile = this->get_override( "WriteDataToVisualizerSetupFile" ) )
            func_WriteDataToVisualizerSetupFile( boost::ref(pVizSetupFile) );
        else{
            this->AbstractCellPopulation< 3, 3 >::WriteDataToVisualizerSetupFile( boost::ref(pVizSetupFile) );
        }
    }
    
    void default_WriteDataToVisualizerSetupFile( ::out_stream & pVizSetupFile ) {
        AbstractCellPopulation< 3, 3 >::WriteDataToVisualizerSetupFile( boost::ref(pVizSetupFile) );
    }

    virtual void WriteResultsToFiles( ::std::string const & rDirectory ) {
        if( bp::override func_WriteResultsToFiles = this->get_override( "WriteResultsToFiles" ) )
            func_WriteResultsToFiles( rDirectory );
        else{
            this->AbstractCellPopulation< 3, 3 >::WriteResultsToFiles( rDirectory );
        }
    }
    
    void default_WriteResultsToFiles( ::std::string const & rDirectory ) {
        AbstractCellPopulation< 3, 3 >::WriteResultsToFiles( rDirectory );
    }

};

void register_CaBasedCellPopulation3_class(){

    { //::CaBasedCellPopulation< 3 >
        typedef bp::class_< CaBasedCellPopulation_less__3__greater__wrapper, bp::bases< AbstractOnLatticeCellPopulation< 3 > >, boost::noncopyable > CaBasedCellPopulation3_exposer_t;
        CaBasedCellPopulation3_exposer_t CaBasedCellPopulation3_exposer = CaBasedCellPopulation3_exposer_t( "CaBasedCellPopulation3", bp::init< PottsMesh< 3 > &, std::vector< boost::shared_ptr<Cell> > &, std::vector< unsigned int >, bp::optional< unsigned int, bool, bool > >(( bp::arg("rMesh"), bp::arg("rCells"), bp::arg("locationIndices"), bp::arg("latticeCarryingCapacity")=(unsigned int)(1U), bp::arg("deleteMesh")=(bool)(false), bp::arg("validate")=(bool)(false) )) );
        bp::scope CaBasedCellPopulation3_scope( CaBasedCellPopulation3_exposer );
        CaBasedCellPopulation3_exposer.def( bp::init< PottsMesh< 3 > & >(( bp::arg("rMesh") )) );
        bp::implicitly_convertible< PottsMesh< 3 > &, CaBasedCellPopulation< 3 > >();
        { //::CaBasedCellPopulation< 3 >::AcceptCellWriter
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AcceptCellWriter_function_type)( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > >,::CellPtr ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AcceptCellWriter_function_type)( ::boost::shared_ptr< AbstractCellWriter< 3, 3 > >,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AcceptCellWriter"
                , AcceptCellWriter_function_type(&::CaBasedCellPopulation< 3 >::AcceptCellWriter)
                , default_AcceptCellWriter_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AcceptCellWriter)
                , ( bp::arg("pCellWriter"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AcceptPopulationCountWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AcceptPopulationCountWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationCountWriter< 3, 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AcceptPopulationCountWriter"
                , AcceptPopulationCountWriter_function_type(&::CaBasedCellPopulation< 3 >::AcceptPopulationCountWriter)
                , default_AcceptPopulationCountWriter_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AcceptPopulationCountWriter)
                , ( bp::arg("pPopulationCountWriter") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AcceptPopulationWriter
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AcceptPopulationWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AcceptPopulationWriter_function_type)( ::boost::shared_ptr< AbstractCellPopulationWriter< 3, 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AcceptPopulationWriter"
                , AcceptPopulationWriter_function_type(&::CaBasedCellPopulation< 3 >::AcceptPopulationWriter)
                , default_AcceptPopulationWriter_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AcceptPopulationWriter)
                , ( bp::arg("pPopulationWriter") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AddCell
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::CellPtr ( exported_class_t::*AddCell_function_type)( ::CellPtr,::CellPtr ) ;
            typedef ::CellPtr ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AddCell_function_type)( ::CellPtr,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AddCell"
                , AddCell_function_type(&::CaBasedCellPopulation< 3 >::AddCell)
                , default_AddCell_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AddCell)
                , ( bp::arg("pNewCell"), bp::arg("pParentCell")=::CellPtr( ) ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AddCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AddCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AddCellUsingLocationIndex"
                , AddCellUsingLocationIndex_function_type(&::CaBasedCellPopulation< 3 >::AddCellUsingLocationIndex)
                , default_AddCellUsingLocationIndex_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AddCellUsingLocationIndex)
                , ( bp::arg("index"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::AddUpdateRule
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*AddUpdateRule_function_type)( ::boost::shared_ptr< AbstractUpdateRule< 3 > > ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_AddUpdateRule_function_type)( ::boost::shared_ptr< AbstractUpdateRule< 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AddUpdateRule"
                , AddUpdateRule_function_type(&::CaBasedCellPopulation< 3 >::AddUpdateRule)
                , default_AddUpdateRule_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_AddUpdateRule)
                , ( bp::arg("pUpdateRule") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*EvaluateDivisionPropensity_function_type)( unsigned int,unsigned int,::CellPtr ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_EvaluateDivisionPropensity_function_type)( unsigned int,unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "EvaluateDivisionPropensity"
                , EvaluateDivisionPropensity_function_type(&::CaBasedCellPopulation< 3 >::EvaluateDivisionPropensity)
                , default_EvaluateDivisionPropensity_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_EvaluateDivisionPropensity)
                , ( bp::arg("currentNodeIndex"), bp::arg("targetNodeIndex"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetCaBasedDivisionRule
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::boost::shared_ptr< AbstractCaBasedDivisionRule< 3 > > ( exported_class_t::*GetCaBasedDivisionRule_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetCaBasedDivisionRule"
                , GetCaBasedDivisionRule_function_type( &::CaBasedCellPopulation< 3 >::GetCaBasedDivisionRule ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetCellDataItemAtPdeNode
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*GetCellDataItemAtPdeNode_function_type)( unsigned int,::std::string &,bool,double ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetCellDataItemAtPdeNode_function_type)( unsigned int,::std::string &,bool,double ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetCellDataItemAtPdeNode"
                , GetCellDataItemAtPdeNode_function_type(&::CaBasedCellPopulation< 3 >::GetCellDataItemAtPdeNode)
                , default_GetCellDataItemAtPdeNode_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetCellDataItemAtPdeNode)
                , ( bp::arg("pdeNodeIndex"), bp::arg("rVariableName"), bp::arg("dirichletBoundaryConditionApplies")=(bool)(false), bp::arg("dirichletBoundaryValue")=0. ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetLocationOfCellCentre
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::boost::numeric::ublas::c_vector< double, 3 > ( exported_class_t::*GetLocationOfCellCentre_function_type)( ::CellPtr ) ;
            typedef ::boost::numeric::ublas::c_vector< double, 3 > ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetLocationOfCellCentre_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetLocationOfCellCentre"
                , GetLocationOfCellCentre_function_type(&::CaBasedCellPopulation< 3 >::GetLocationOfCellCentre)
                , default_GetLocationOfCellCentre_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetLocationOfCellCentre)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::std::set< unsigned int > ( exported_class_t::*GetNeighbouringLocationIndices_function_type)( ::CellPtr ) ;
            typedef ::std::set< unsigned int > ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetNeighbouringLocationIndices_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetNeighbouringLocationIndices"
                , GetNeighbouringLocationIndices_function_type(&::CaBasedCellPopulation< 3 >::GetNeighbouringLocationIndices)
                , default_GetNeighbouringLocationIndices_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetNeighbouringLocationIndices)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetNode
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::Node< 3 > * ( exported_class_t::*GetNode_function_type)( unsigned int ) ;
            typedef ::Node< 3 > * ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetNode_function_type)( unsigned int ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetNode"
                , GetNode_function_type(&::CaBasedCellPopulation< 3 >::GetNode)
                , default_GetNode_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetNode)
                , ( bp::arg("index") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetNodeCorrespondingToCell
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::Node< 3 > * ( exported_class_t::*GetNodeCorrespondingToCell_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetNodeCorrespondingToCell"
                , GetNodeCorrespondingToCell_function_type( &::CaBasedCellPopulation< 3 >::GetNodeCorrespondingToCell )
                , ( bp::arg("pCell") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetNumNodes
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef unsigned int ( exported_class_t::*GetNumNodes_function_type)(  ) ;
            typedef unsigned int ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetNumNodes_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetNumNodes"
                , GetNumNodes_function_type(&::CaBasedCellPopulation< 3 >::GetNumNodes)
                , default_GetNumNodes_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetNumNodes) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetTetrahedralMeshForPdeModifier
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::TetrahedralMesh< 3, 3 > * ( exported_class_t::*GetTetrahedralMeshForPdeModifier_function_type)(  ) ;
            typedef ::TetrahedralMesh< 3, 3 > * ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetTetrahedralMeshForPdeModifier_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetTetrahedralMeshForPdeModifier"
                , GetTetrahedralMeshForPdeModifier_function_type(&::CaBasedCellPopulation< 3 >::GetTetrahedralMeshForPdeModifier)
                , default_GetTetrahedralMeshForPdeModifier_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetTetrahedralMeshForPdeModifier)
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetUpdateRuleCollection
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::std::vector< boost::shared_ptr<AbstractUpdateRule<3> > > const ( exported_class_t::*GetUpdateRuleCollection_function_type)(  ) const;
            typedef ::std::vector< boost::shared_ptr<AbstractUpdateRule<3> > > const ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetUpdateRuleCollection_function_type)(  ) const;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetUpdateRuleCollection"
                , GetUpdateRuleCollection_function_type(&::CaBasedCellPopulation< 3 >::GetUpdateRuleCollection)
                , default_GetUpdateRuleCollection_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetUpdateRuleCollection) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetVolumeOfCell
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*GetVolumeOfCell_function_type)( ::CellPtr ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetVolumeOfCell_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetVolumeOfCell"
                , GetVolumeOfCell_function_type(&::CaBasedCellPopulation< 3 >::GetVolumeOfCell)
                , default_GetVolumeOfCell_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetVolumeOfCell)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::GetWidth
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*GetWidth_function_type)( unsigned int const & ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetWidth_function_type)( unsigned int const & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetWidth"
                , GetWidth_function_type(&::CaBasedCellPopulation< 3 >::GetWidth)
                , default_GetWidth_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetWidth)
                , ( bp::arg("rDimension") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsCellAssociatedWithADeletedLocation_function_type)( ::CellPtr ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsCellAssociatedWithADeletedLocation_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsCellAssociatedWithADeletedLocation"
                , IsCellAssociatedWithADeletedLocation_function_type(&::CaBasedCellPopulation< 3 >::IsCellAssociatedWithADeletedLocation)
                , default_IsCellAssociatedWithADeletedLocation_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsCellAssociatedWithADeletedLocation)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::IsPdeNodeAssociatedWithNonApoptoticCell
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsPdeNodeAssociatedWithNonApoptoticCell_function_type)( unsigned int ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsPdeNodeAssociatedWithNonApoptoticCell_function_type)( unsigned int ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsPdeNodeAssociatedWithNonApoptoticCell"
                , IsPdeNodeAssociatedWithNonApoptoticCell_function_type(&::CaBasedCellPopulation< 3 >::IsPdeNodeAssociatedWithNonApoptoticCell)
                , default_IsPdeNodeAssociatedWithNonApoptoticCell_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsPdeNodeAssociatedWithNonApoptoticCell)
                , ( bp::arg("pdeNodeIndex") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::IsRoomToDivide
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsRoomToDivide_function_type)( ::CellPtr ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsRoomToDivide_function_type)( ::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsRoomToDivide"
                , IsRoomToDivide_function_type(&::CaBasedCellPopulation< 3 >::IsRoomToDivide)
                , default_IsRoomToDivide_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsRoomToDivide)
                , ( bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::IsSiteAvailable
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsSiteAvailable_function_type)( unsigned int,::CellPtr ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsSiteAvailable_function_type)( unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsSiteAvailable"
                , IsSiteAvailable_function_type(&::CaBasedCellPopulation< 3 >::IsSiteAvailable)
                , default_IsSiteAvailable_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsSiteAvailable)
                , ( bp::arg("index"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::OpenWritersFiles
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*OpenWritersFiles_function_type)( ::OutputFileHandler & ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_OpenWritersFiles_function_type)( ::OutputFileHandler & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "OpenWritersFiles"
                , OpenWritersFiles_function_type(&::CaBasedCellPopulation< 3 >::OpenWritersFiles)
                , default_OpenWritersFiles_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_OpenWritersFiles)
                , ( bp::arg("rOutputFileHandler") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::OutputCellPopulationParameters
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*OutputCellPopulationParameters_function_type)( ::out_stream & ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_OutputCellPopulationParameters_function_type)( ::out_stream & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "OutputCellPopulationParameters"
                , OutputCellPopulationParameters_function_type(&::CaBasedCellPopulation< 3 >::OutputCellPopulationParameters)
                , default_OutputCellPopulationParameters_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_OutputCellPopulationParameters)
                , ( bp::arg("rParamsFile") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::RemoveAllUpdateRules
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*RemoveAllUpdateRules_function_type)(  ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_RemoveAllUpdateRules_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "RemoveAllUpdateRules"
                , RemoveAllUpdateRules_function_type(&::CaBasedCellPopulation< 3 >::RemoveAllUpdateRules)
                , default_RemoveAllUpdateRules_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_RemoveAllUpdateRules) );
        
        }
        { //::CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*RemoveCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_RemoveCellUsingLocationIndex_function_type)( unsigned int,::CellPtr ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "RemoveCellUsingLocationIndex"
                , RemoveCellUsingLocationIndex_function_type(&::CaBasedCellPopulation< 3 >::RemoveCellUsingLocationIndex)
                , default_RemoveCellUsingLocationIndex_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_RemoveCellUsingLocationIndex)
                , ( bp::arg("index"), bp::arg("pCell") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::RemoveDeadCells
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef unsigned int ( exported_class_t::*RemoveDeadCells_function_type)(  ) ;
            typedef unsigned int ( CaBasedCellPopulation_less__3__greater__wrapper::*default_RemoveDeadCells_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "RemoveDeadCells"
                , RemoveDeadCells_function_type(&::CaBasedCellPopulation< 3 >::RemoveDeadCells)
                , default_RemoveDeadCells_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_RemoveDeadCells) );
        
        }
        { //::CaBasedCellPopulation< 3 >::SetCaBasedDivisionRule
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetCaBasedDivisionRule_function_type)( ::boost::shared_ptr< AbstractCaBasedDivisionRule< 3 > > ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "SetCaBasedDivisionRule"
                , SetCaBasedDivisionRule_function_type( &::CaBasedCellPopulation< 3 >::SetCaBasedDivisionRule )
                , ( bp::arg("pCaBasedDivisionRule") ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::Update
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*Update_function_type)( bool ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_Update_function_type)( bool ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "Update"
                , Update_function_type(&::CaBasedCellPopulation< 3 >::Update)
                , default_Update_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_Update)
                , ( bp::arg("hasHadBirthsOrDeaths")=(bool)(true) ) );
        
        }
        { //::CaBasedCellPopulation< 3 >::UpdateCellLocations
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*UpdateCellLocations_function_type)( double ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_UpdateCellLocations_function_type)( double ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "UpdateCellLocations"
                , UpdateCellLocations_function_type(&::CaBasedCellPopulation< 3 >::UpdateCellLocations)
                , default_UpdateCellLocations_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_UpdateCellLocations)
                , ( bp::arg("dt") ) );
        
        }
        { //::AbstractCellPopulation< 3, 3 >::AcceptCellWritersAcrossPopulation
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*AcceptCellWritersAcrossPopulation_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "AcceptCellWritersAcrossPopulation"
                , AcceptCellWritersAcrossPopulation_function_type( &CaBasedCellPopulation_less__3__greater__wrapper::default_AcceptCellWritersAcrossPopulation ) );
        
        }
        { //::AbstractCellPopulation< 3, 3 >::GetCellUsingLocationIndex
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::CellPtr ( exported_class_t::*GetCellUsingLocationIndex_function_type)( unsigned int ) ;
            typedef ::CellPtr ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetCellUsingLocationIndex_function_type)( unsigned int ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetCellUsingLocationIndex"
                , GetCellUsingLocationIndex_function_type(&::AbstractCellPopulation< 3, 3 >::GetCellUsingLocationIndex)
                , default_GetCellUsingLocationIndex_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetCellUsingLocationIndex)
                , ( bp::arg("index") ) );
        
        }
        { //::AbstractOnLatticeCellPopulation< 3 >::GetDefaultTimeStep
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef double ( exported_class_t::*GetDefaultTimeStep_function_type)(  ) ;
            typedef double ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetDefaultTimeStep_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetDefaultTimeStep"
                , GetDefaultTimeStep_function_type(&::AbstractOnLatticeCellPopulation< 3 >::GetDefaultTimeStep)
                , default_GetDefaultTimeStep_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetDefaultTimeStep) );
        
        }
        { //::AbstractOnLatticeCellPopulation< 3 >::GetNeighbouringNodeIndices
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef ::std::set< unsigned int > ( exported_class_t::*GetNeighbouringNodeIndices_function_type)( unsigned int ) ;
            typedef ::std::set< unsigned int > ( CaBasedCellPopulation_less__3__greater__wrapper::*default_GetNeighbouringNodeIndices_function_type)( unsigned int ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "GetNeighbouringNodeIndices"
                , GetNeighbouringNodeIndices_function_type(&::AbstractOnLatticeCellPopulation< 3 >::GetNeighbouringNodeIndices)
                , default_GetNeighbouringNodeIndices_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_GetNeighbouringNodeIndices)
                , ( bp::arg("index") ) );
        
        }
        { //::AbstractCellPopulation< 3, 3 >::IsCellAttachedToLocationIndex
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef bool ( exported_class_t::*IsCellAttachedToLocationIndex_function_type)( unsigned int ) ;
            typedef bool ( CaBasedCellPopulation_less__3__greater__wrapper::*default_IsCellAttachedToLocationIndex_function_type)( unsigned int ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "IsCellAttachedToLocationIndex"
                , IsCellAttachedToLocationIndex_function_type(&::AbstractCellPopulation< 3, 3 >::IsCellAttachedToLocationIndex)
                , default_IsCellAttachedToLocationIndex_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_IsCellAttachedToLocationIndex)
                , ( bp::arg("index") ) );
        
        }
        { //::AbstractOnLatticeCellPopulation< 3 >::SetNode
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*SetNode_function_type)( unsigned int,::ChastePoint< 3 > & ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_SetNode_function_type)( unsigned int,::ChastePoint< 3 > & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "SetNode"
                , SetNode_function_type(&::AbstractOnLatticeCellPopulation< 3 >::SetNode)
                , default_SetNode_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_SetNode)
                , ( bp::arg("index"), bp::arg("rNewLocation") ) );
        
        }
        { //::AbstractCellPopulation< 3, 3 >::SimulationSetupHook
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*SimulationSetupHook_function_type)( ::AbstractCellBasedSimulation< 3, 3 > * ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_SimulationSetupHook_function_type)( ::AbstractCellBasedSimulation< 3, 3 > * ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "SimulationSetupHook"
                , SimulationSetupHook_function_type(&::AbstractCellPopulation< 3, 3 >::SimulationSetupHook)
                , default_SimulationSetupHook_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_SimulationSetupHook)
                , ( bp::arg("pSimulation") ) );
        
        }
        { //::AbstractCellPopulation< 3, 3 >::UpdateCellProcessLocation
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*UpdateCellProcessLocation_function_type)(  ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_UpdateCellProcessLocation_function_type)(  ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "UpdateCellProcessLocation"
                , UpdateCellProcessLocation_function_type(&::AbstractCellPopulation< 3, 3 >::UpdateCellProcessLocation)
                , default_UpdateCellProcessLocation_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_UpdateCellProcessLocation) );
        
        }
        { //::AbstractCellPopulation< 3, 3 >::WriteDataToVisualizerSetupFile
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*WriteDataToVisualizerSetupFile_function_type)( ::out_stream & ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_WriteDataToVisualizerSetupFile_function_type)( ::out_stream & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "WriteDataToVisualizerSetupFile"
                , WriteDataToVisualizerSetupFile_function_type(&::AbstractCellPopulation< 3, 3 >::WriteDataToVisualizerSetupFile)
                , default_WriteDataToVisualizerSetupFile_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_WriteDataToVisualizerSetupFile)
                , ( bp::arg("pVizSetupFile") ) );
        
        }
        { //::AbstractCellPopulation< 3, 3 >::WriteResultsToFiles
        
            typedef CaBasedCellPopulation< 3 > exported_class_t;
            typedef void ( exported_class_t::*WriteResultsToFiles_function_type)( ::std::string const & ) ;
            typedef void ( CaBasedCellPopulation_less__3__greater__wrapper::*default_WriteResultsToFiles_function_type)( ::std::string const & ) ;
            
            CaBasedCellPopulation3_exposer.def( 
                "WriteResultsToFiles"
                , WriteResultsToFiles_function_type(&::AbstractCellPopulation< 3, 3 >::WriteResultsToFiles)
                , default_WriteResultsToFiles_function_type(&CaBasedCellPopulation_less__3__greater__wrapper::default_WriteResultsToFiles)
                , ( bp::arg("rDirectory") ) );
        
        }
        CaBasedCellPopulation3_exposer.def("AddCellWriterCellLabelWriterWriter", &CaBasedCellPopulation<3 >::AddCellWriter<CellLabelWriter>);
        CaBasedCellPopulation3_exposer.def("AddPopulationWriterVoronoiDataWriterWriter", &CaBasedCellPopulation<3 >::AddPopulationWriter<VoronoiDataWriter>);
    }

}
