namespace py = pybind11;

#ifndef CellsGeneratorSimpleOxygenBasedCellCycleModel_3_hpp__pyplusplus_wrapper
#define CellsGeneratorSimpleOxygenBasedCellCycleModel_3_hpp__pyplusplus_wrapper
void register_CellsGeneratorSimpleOxygenBasedCellCycleModel_3_class(py::module &m);
#endif // CellsGeneratorSimpleOxygenBasedCellCycleModel_3_hpp__pyplusplus_wrapper
