namespace py = pybind11;

#ifndef CellsGeneratorNoCellCycleModel_3_hpp__pyplusplus_wrapper
#define CellsGeneratorNoCellCycleModel_3_hpp__pyplusplus_wrapper
void register_CellsGeneratorNoCellCycleModel_3_class(py::module &m);
#endif // CellsGeneratorNoCellCycleModel_3_hpp__pyplusplus_wrapper
