namespace py = pybind11;

#ifndef CellsGeneratorNoCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorNoCellCycleModel_2_hpp__pyplusplus_wrapper
void register_CellsGeneratorNoCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorNoCellCycleModel_2_hpp__pyplusplus_wrapper
