namespace py = pybind11;

#ifndef CellsGeneratorUniformCellCycleModel_3_hpp__pyplusplus_wrapper
#define CellsGeneratorUniformCellCycleModel_3_hpp__pyplusplus_wrapper
void register_CellsGeneratorUniformCellCycleModel_3_class(py::module &m);
#endif // CellsGeneratorUniformCellCycleModel_3_hpp__pyplusplus_wrapper
