namespace py = pybind11;

#ifndef CellsGeneratorUniformG1GenerationalCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorUniformG1GenerationalCellCycleModel_2_hpp__pyplusplus_wrapper
void register_CellsGeneratorUniformG1GenerationalCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorUniformG1GenerationalCellCycleModel_2_hpp__pyplusplus_wrapper
