namespace py = pybind11;

#ifndef CellsGeneratorSimpleOxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper
#define CellsGeneratorSimpleOxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper
void register_CellsGeneratorSimpleOxygenBasedCellCycleModel_2_class(py::module &m);
#endif // CellsGeneratorSimpleOxygenBasedCellCycleModel_2_hpp__pyplusplus_wrapper
