namespace py = pybind11;

#ifndef DifferentialAdhesionPottsUpdateRule2_hpp__pyplusplus_wrapper
#define DifferentialAdhesionPottsUpdateRule2_hpp__pyplusplus_wrapper
void register_DifferentialAdhesionPottsUpdateRule2_class(py::module &m);
#endif // DifferentialAdhesionPottsUpdateRule2_hpp__pyplusplus_wrapper
