namespace py = pybind11;

#ifndef EllipticGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
#define EllipticGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
void register_EllipticGrowingDomainPdeModifier3_class(py::module &m);
#endif // EllipticGrowingDomainPdeModifier3_hpp__pyplusplus_wrapper
