namespace py = pybind11;

#ifndef EllipticGrowingDomainPdeModifier2_hpp__pyplusplus_wrapper
#define EllipticGrowingDomainPdeModifier2_hpp__pyplusplus_wrapper
void register_EllipticGrowingDomainPdeModifier2_class(py::module &m);
#endif // EllipticGrowingDomainPdeModifier2_hpp__pyplusplus_wrapper
