#ifndef GeneralisedLinearSpringForce2_2_hpp__pyplusplus_wrapper
#define GeneralisedLinearSpringForce2_2_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_GeneralisedLinearSpringForce2_2_class(py::module &m);
#endif // GeneralisedLinearSpringForce2_2_hpp__pyplusplus_wrapper
