#ifndef MeshBasedCellPopulationWithGhostNodes3_hpp__pyplusplus_wrapper
#define MeshBasedCellPopulationWithGhostNodes3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_MeshBasedCellPopulationWithGhostNodes3_class(py::module &m);
#endif // MeshBasedCellPopulationWithGhostNodes3_hpp__pyplusplus_wrapper
