namespace py = pybind11;

#ifndef MeshBasedCellPopulationWithGhostNodes3_hpp__pyplusplus_wrapper
#define MeshBasedCellPopulationWithGhostNodes3_hpp__pyplusplus_wrapper
void register_MeshBasedCellPopulationWithGhostNodes3_class(py::module &m);
#endif // MeshBasedCellPopulationWithGhostNodes3_hpp__pyplusplus_wrapper
