namespace py = pybind11;

#ifndef SimpleOxygenBasedCellCycleModel_hpp__pyplusplus_wrapper
#define SimpleOxygenBasedCellCycleModel_hpp__pyplusplus_wrapper
void register_SimpleOxygenBasedCellCycleModel_class(py::module &m);
#endif // SimpleOxygenBasedCellCycleModel_hpp__pyplusplus_wrapper
