#ifndef SphereGeometryBoundaryCondition3_hpp__pyplusplus_wrapper
#define SphereGeometryBoundaryCondition3_hpp__pyplusplus_wrapper

namespace py = pybind11;
void register_SphereGeometryBoundaryCondition3_class(py::module &m);
#endif // SphereGeometryBoundaryCondition3_hpp__pyplusplus_wrapper
