namespace py = pybind11;

#ifndef SphereGeometryBoundaryCondition3_hpp__pyplusplus_wrapper
#define SphereGeometryBoundaryCondition3_hpp__pyplusplus_wrapper
void register_SphereGeometryBoundaryCondition3_class(py::module &m);
#endif // SphereGeometryBoundaryCondition3_hpp__pyplusplus_wrapper
