namespace py = pybind11;

#ifndef SphereGeometryBoundaryCondition2_hpp__pyplusplus_wrapper
#define SphereGeometryBoundaryCondition2_hpp__pyplusplus_wrapper
void register_SphereGeometryBoundaryCondition2_class(py::module &m);
#endif // SphereGeometryBoundaryCondition2_hpp__pyplusplus_wrapper
