namespace py = pybind11;

#ifndef UniformG1GenerationalCellCycleModel_hpp__pyplusplus_wrapper
#define UniformG1GenerationalCellCycleModel_hpp__pyplusplus_wrapper
void register_UniformG1GenerationalCellCycleModel_class(py::module &m);
#endif // UniformG1GenerationalCellCycleModel_hpp__pyplusplus_wrapper
