#ifndef UniformG1GenerationalCellCycleModel_hpp__pyplusplus_wrapper
#define UniformG1GenerationalCellCycleModel_hpp__pyplusplus_wrapper
namespace py = pybind11;
void register_UniformG1GenerationalCellCycleModel_class(py::module &m);
#endif // UniformG1GenerationalCellCycleModel_hpp__pyplusplus_wrapper
