namespace py = pybind11;

#ifndef VolumeConstraintPottsUpdateRule3_hpp__pyplusplus_wrapper
#define VolumeConstraintPottsUpdateRule3_hpp__pyplusplus_wrapper
void register_VolumeConstraintPottsUpdateRule3_class(py::module &m);
#endif // VolumeConstraintPottsUpdateRule3_hpp__pyplusplus_wrapper
