namespace py = pybind11;

#ifndef AbstractPyChasteActorGenerator2_hpp__pyplusplus_wrapper
#define AbstractPyChasteActorGenerator2_hpp__pyplusplus_wrapper
void register_AbstractPyChasteActorGenerator2_class(py::module &m);
#endif // AbstractPyChasteActorGenerator2_hpp__pyplusplus_wrapper
