namespace py = pybind11;

#ifndef AbstractPyChasteActorGenerator3_hpp__pyplusplus_wrapper
#define AbstractPyChasteActorGenerator3_hpp__pyplusplus_wrapper
void register_AbstractPyChasteActorGenerator3_class(py::module &m);
#endif // AbstractPyChasteActorGenerator3_hpp__pyplusplus_wrapper
