// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "ReplicatableVector.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_OPAQUE_SPECIALIZED_TYPE_ID( _p_Vec )

void register_ReplicatableVector_class(){

    { //::ReplicatableVector
        typedef bp::class_< ReplicatableVector > ReplicatableVector_exposer_t;
        ReplicatableVector_exposer_t ReplicatableVector_exposer = ReplicatableVector_exposer_t( "ReplicatableVector", bp::init< >() );
        bp::scope ReplicatableVector_scope( ReplicatableVector_exposer );
        ReplicatableVector_exposer.def( bp::init< Vec >(( bp::arg("vec") )) );
        bp::implicitly_convertible< Vec, ReplicatableVector >();
        ReplicatableVector_exposer.def( bp::init< unsigned int >(( bp::arg("size") )) );
        bp::implicitly_convertible< unsigned int, ReplicatableVector >();
        { //::ReplicatableVector::GetSize
        
            typedef unsigned int ( ::ReplicatableVector::*GetSize_function_type)(  ) ;
            
            ReplicatableVector_exposer.def( 
                "GetSize"
                , GetSize_function_type( &::ReplicatableVector::GetSize ) );
        
        }
        { //::ReplicatableVector::Replicate
        
            typedef void ( ::ReplicatableVector::*Replicate_function_type)( unsigned int,unsigned int ) ;
            
            ReplicatableVector_exposer.def( 
                "Replicate"
                , Replicate_function_type( &::ReplicatableVector::Replicate )
                , ( bp::arg("lo"), bp::arg("hi") ) );
        
        }
        { //::ReplicatableVector::ReplicatePetscVector
        
            typedef void ( ::ReplicatableVector::*ReplicatePetscVector_function_type)( ::Vec ) ;
            
            ReplicatableVector_exposer.def( 
                "ReplicatePetscVector"
                , ReplicatePetscVector_function_type( &::ReplicatableVector::ReplicatePetscVector )
                , ( bp::arg("vec") ) );
        
        }
        { //::ReplicatableVector::Resize
        
            typedef void ( ::ReplicatableVector::*Resize_function_type)( unsigned int ) ;
            
            ReplicatableVector_exposer.def( 
                "Resize"
                , Resize_function_type( &::ReplicatableVector::Resize )
                , ( bp::arg("size") ) );
        
        }
        { //::ReplicatableVector::operator[]
        
            typedef double & ( ::ReplicatableVector::*__getitem___function_type)( unsigned int ) ;
            
            ReplicatableVector_exposer.def( 
                "__getitem__"
                , __getitem___function_type( &::ReplicatableVector::operator[] )
                , ( bp::arg("index") )
                , bp::return_value_policy< bp::copy_non_const_reference >() );
        
        }
    }

}
