// This file has been generated by Py++.


/*

Copyright (c) 2005-2016, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "mesh_headers.hpp"
#include "AbstractMesh3_3.pypp.hpp"

namespace bp = boost::python;

struct AbstractMesh_less__3_comma__3__greater__wrapper : AbstractMesh< 3, 3 >, bp::wrapper< AbstractMesh< 3, 3 > > {

    AbstractMesh_less__3_comma__3__greater__wrapper( )
    : AbstractMesh<3, 3>( )
      , bp::wrapper< AbstractMesh< 3, 3 > >(){
        // null constructor
    
    }

    virtual ::ChasteCuboid< 3 > CalculateBoundingBox(  ) const  {
        if( bp::override func_CalculateBoundingBox = this->get_override( "CalculateBoundingBox" ) )
            return func_CalculateBoundingBox(  );
        else{
            return this->AbstractMesh< 3, 3 >::CalculateBoundingBox(  );
        }
    }
    
    ::ChasteCuboid< 3 > default_CalculateBoundingBox(  ) const  {
        return AbstractMesh< 3, 3 >::CalculateBoundingBox( );
    }

    ::ChasteCuboid< 3 > CalculateBoundingBox( ::std::vector< Node<3> * > const & rNodes ) const {
        return AbstractMesh< 3, 3 >::CalculateBoundingBox( boost::ref(rNodes) );
    }

    virtual unsigned int GetNearestNodeIndex( ::ChastePoint< 3 > const & rTestPoint ) {
        if( bp::override func_GetNearestNodeIndex = this->get_override( "GetNearestNodeIndex" ) )
            return func_GetNearestNodeIndex( boost::ref(rTestPoint) );
        else{
            return this->AbstractMesh< 3, 3 >::GetNearestNodeIndex( boost::ref(rTestPoint) );
        }
    }
    
    unsigned int default_GetNearestNodeIndex( ::ChastePoint< 3 > const & rTestPoint ) {
        return AbstractMesh< 3, 3 >::GetNearestNodeIndex( boost::ref(rTestPoint) );
    }

    virtual unsigned int GetNumAllNodes(  ) const  {
        if( bp::override func_GetNumAllNodes = this->get_override( "GetNumAllNodes" ) )
            return func_GetNumAllNodes(  );
        else{
            return this->AbstractMesh< 3, 3 >::GetNumAllNodes(  );
        }
    }
    
    unsigned int default_GetNumAllNodes(  ) const  {
        return AbstractMesh< 3, 3 >::GetNumAllNodes( );
    }

    virtual unsigned int GetNumNodes(  ) const  {
        if( bp::override func_GetNumNodes = this->get_override( "GetNumNodes" ) )
            return func_GetNumNodes(  );
        else{
            return this->AbstractMesh< 3, 3 >::GetNumNodes(  );
        }
    }
    
    unsigned int default_GetNumNodes(  ) const  {
        return AbstractMesh< 3, 3 >::GetNumNodes( );
    }

    virtual ::boost::numeric::ublas::c_vector< double, 3 > GetVectorFromAtoB( ::boost::numeric::ublas::c_vector< double, 3 > const & rLocationA, ::boost::numeric::ublas::c_vector< double, 3 > const & rLocationB ) {
        if( bp::override func_GetVectorFromAtoB = this->get_override( "GetVectorFromAtoB" ) )
            return func_GetVectorFromAtoB( boost::ref(rLocationA), boost::ref(rLocationB) );
        else{
            return this->AbstractMesh< 3, 3 >::GetVectorFromAtoB( boost::ref(rLocationA), boost::ref(rLocationB) );
        }
    }
    
    ::boost::numeric::ublas::c_vector< double, 3 > default_GetVectorFromAtoB( ::boost::numeric::ublas::c_vector< double, 3 > const & rLocationA, ::boost::numeric::ublas::c_vector< double, 3 > const & rLocationB ) {
        return AbstractMesh< 3, 3 >::GetVectorFromAtoB( boost::ref(rLocationA), boost::ref(rLocationB) );
    }

    virtual double GetWidth( unsigned int const & rDimension ) const  {
        if( bp::override func_GetWidth = this->get_override( "GetWidth" ) )
            return func_GetWidth( rDimension );
        else{
            return this->AbstractMesh< 3, 3 >::GetWidth( rDimension );
        }
    }
    
    double default_GetWidth( unsigned int const & rDimension ) const  {
        return AbstractMesh< 3, 3 >::GetWidth( rDimension );
    }

    virtual void PermuteNodes(  ) {
        if( bp::override func_PermuteNodes = this->get_override( "PermuteNodes" ) )
            func_PermuteNodes(  );
        else{
            this->AbstractMesh< 3, 3 >::PermuteNodes(  );
        }
    }
    
    void default_PermuteNodes(  ) {
        AbstractMesh< 3, 3 >::PermuteNodes( );
    }

    virtual void ReadNodesPerProcessorFile( ::std::string const & rNodesPerProcessorFile ) {
        if( bp::override func_ReadNodesPerProcessorFile = this->get_override( "ReadNodesPerProcessorFile" ) )
            func_ReadNodesPerProcessorFile( rNodesPerProcessorFile );
        else{
            this->AbstractMesh< 3, 3 >::ReadNodesPerProcessorFile( rNodesPerProcessorFile );
        }
    }
    
    void default_ReadNodesPerProcessorFile( ::std::string const & rNodesPerProcessorFile ) {
        AbstractMesh< 3, 3 >::ReadNodesPerProcessorFile( rNodesPerProcessorFile );
    }

    virtual void RefreshMesh(  ) {
        if( bp::override func_RefreshMesh = this->get_override( "RefreshMesh" ) )
            func_RefreshMesh(  );
        else{
            this->AbstractMesh< 3, 3 >::RefreshMesh(  );
        }
    }
    
    void default_RefreshMesh(  ) {
        AbstractMesh< 3, 3 >::RefreshMesh( );
    }

    virtual void Rotate( ::boost::numeric::ublas::c_matrix< double, 3, 3 > rotationMatrix ) {
        if( bp::override func_Rotate = this->get_override( "Rotate" ) )
            func_Rotate( rotationMatrix );
        else{
            this->AbstractMesh< 3, 3 >::Rotate( rotationMatrix );
        }
    }
    
    void default_Rotate( ::boost::numeric::ublas::c_matrix< double, 3, 3 > rotationMatrix ) {
        AbstractMesh< 3, 3 >::Rotate( rotationMatrix );
    }

    virtual void Scale( double const xFactor=1., double const yFactor=1., double const zFactor=1. ) {
        if( bp::override func_Scale = this->get_override( "Scale" ) )
            func_Scale( xFactor, yFactor, zFactor );
        else{
            this->AbstractMesh< 3, 3 >::Scale( xFactor, yFactor, zFactor );
        }
    }
    
    void default_Scale( double const xFactor=1., double const yFactor=1., double const zFactor=1. ) {
        AbstractMesh< 3, 3 >::Scale( xFactor, yFactor, zFactor );
    }

    virtual void SetDistributedVectorFactory( ::DistributedVectorFactory * pFactory ) {
        if( bp::override func_SetDistributedVectorFactory = this->get_override( "SetDistributedVectorFactory" ) )
            func_SetDistributedVectorFactory( boost::python::ptr(pFactory) );
        else{
            this->AbstractMesh< 3, 3 >::SetDistributedVectorFactory( boost::python::ptr(pFactory) );
        }
    }
    
    void default_SetDistributedVectorFactory( ::DistributedVectorFactory * pFactory ) {
        AbstractMesh< 3, 3 >::SetDistributedVectorFactory( boost::python::ptr(pFactory) );
    }

    virtual void SetElementOwnerships(  ){
        if( bp::override func_SetElementOwnerships = this->get_override( "SetElementOwnerships" ) )
            func_SetElementOwnerships(  );
        else{
            this->AbstractMesh< 3, 3 >::SetElementOwnerships(  );
        }
    }
    
    virtual void default_SetElementOwnerships(  ){
        AbstractMesh< 3, 3 >::SetElementOwnerships( );
    }

    virtual unsigned int SolveNodeMapping( unsigned int index ) const {
        bp::override func_SolveNodeMapping = this->get_override( "SolveNodeMapping" );
        return func_SolveNodeMapping( index );
    }

    virtual void Translate( ::boost::numeric::ublas::c_vector< double, 3 > const & rDisplacement ) {
        if( bp::override func_Translate = this->get_override( "Translate" ) )
            func_Translate( boost::ref(rDisplacement) );
        else{
            this->AbstractMesh< 3, 3 >::Translate( boost::ref(rDisplacement) );
        }
    }
    
    void default_Translate( ::boost::numeric::ublas::c_vector< double, 3 > const & rDisplacement ) {
        AbstractMesh< 3, 3 >::Translate( boost::ref(rDisplacement) );
    }

};

void register_AbstractMesh3_3_class(){

    bp::class_< AbstractMesh_less__3_comma__3__greater__wrapper, boost::noncopyable >( "AbstractMesh3_3", bp::init< >() )    
        .def( 
            "CalculateBoundingBox"
            , (::ChasteCuboid< 3 > ( ::AbstractMesh<3, 3>::* )(  )const)(&::AbstractMesh< 3, 3 >::CalculateBoundingBox)
            , (::ChasteCuboid< 3 > ( AbstractMesh_less__3_comma__3__greater__wrapper::* )(  )const)(&AbstractMesh_less__3_comma__3__greater__wrapper::default_CalculateBoundingBox) )    
        .def( 
            "CalculateBoundingBox"
            , (::ChasteCuboid<3> ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( ::std::vector<Node<3> *, std::allocator<Node<3> *> > const & )const)(&AbstractMesh_less__3_comma__3__greater__wrapper::CalculateBoundingBox)
            , ( bp::arg("rNodes") ) )    
        .def( 
            "CalculateMaximumContainingElementsPerProcess"
            , (unsigned int ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::CalculateMaximumContainingElementsPerProcess ) )    
        .def( 
            "GetBoundaryNodeIteratorBegin"
            , (::AbstractMesh< 3, 3 >::BoundaryNodeIterator ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::GetBoundaryNodeIteratorBegin ) )    
        .def( 
            "GetBoundaryNodeIteratorEnd"
            , (::AbstractMesh< 3, 3 >::BoundaryNodeIterator ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::GetBoundaryNodeIteratorEnd ) )    
        .def( 
            "GetDistanceBetweenNodes"
            , (double ( ::AbstractMesh<3, 3>::* )( unsigned int,unsigned int ))( &::AbstractMesh< 3, 3 >::GetDistanceBetweenNodes )
            , ( bp::arg("indexA"), bp::arg("indexB") ) )    
        .def( 
            "GetMeshFileBaseName"
            , (::std::string ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::GetMeshFileBaseName ) )    
        .def( 
            "GetNearestNodeIndex"
            , (unsigned int ( ::AbstractMesh<3, 3>::* )( ::ChastePoint< 3 > const & ))(&::AbstractMesh< 3, 3 >::GetNearestNodeIndex)
            , (unsigned int ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( ::ChastePoint< 3 > const & ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_GetNearestNodeIndex)
            , ( bp::arg("rTestPoint") ) )    
        .def( 
            "GetNodeIteratorBegin"
            , (::AbstractMesh< 3, 3 >::NodeIterator ( ::AbstractMesh<3, 3>::* )( bool ))( &::AbstractMesh< 3, 3 >::GetNodeIteratorBegin )
            , ( bp::arg("skipDeletedNodes")=(bool)(true) ) )    
        .def( 
            "GetNodeIteratorEnd"
            , (::AbstractMesh< 3, 3 >::NodeIterator ( ::AbstractMesh<3, 3>::* )(  ))( &::AbstractMesh< 3, 3 >::GetNodeIteratorEnd ) )    
        .def( 
            "GetNumAllNodes"
            , (unsigned int ( ::AbstractMesh<3, 3>::* )(  )const)(&::AbstractMesh< 3, 3 >::GetNumAllNodes)
            , (unsigned int ( AbstractMesh_less__3_comma__3__greater__wrapper::* )(  )const)(&AbstractMesh_less__3_comma__3__greater__wrapper::default_GetNumAllNodes) )    
        .def( 
            "GetNumBoundaryNodes"
            , (unsigned int ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::GetNumBoundaryNodes ) )    
        .def( 
            "GetNumNodeAttributes"
            , (unsigned int ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::GetNumNodeAttributes ) )    
        .def( 
            "GetNumNodes"
            , (unsigned int ( ::AbstractMesh<3, 3>::* )(  )const)(&::AbstractMesh< 3, 3 >::GetNumNodes)
            , (unsigned int ( AbstractMesh_less__3_comma__3__greater__wrapper::* )(  )const)(&AbstractMesh_less__3_comma__3__greater__wrapper::default_GetNumNodes) )    
        .def( 
            "GetVectorFromAtoB"
            , (::boost::numeric::ublas::c_vector< double, 3 > ( ::AbstractMesh<3, 3>::* )( ::boost::numeric::ublas::c_vector< double, 3 > const &,::boost::numeric::ublas::c_vector< double, 3 > const & ))(&::AbstractMesh< 3, 3 >::GetVectorFromAtoB)
            , (::boost::numeric::ublas::c_vector< double, 3 > ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( ::boost::numeric::ublas::c_vector< double, 3 > const &,::boost::numeric::ublas::c_vector< double, 3 > const & ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_GetVectorFromAtoB)
            , ( bp::arg("rLocationA"), bp::arg("rLocationB") ) )    
        .def( 
            "GetWidth"
            , (double ( ::AbstractMesh<3, 3>::* )( unsigned int const & )const)(&::AbstractMesh< 3, 3 >::GetWidth)
            , (double ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( unsigned int const & )const)(&AbstractMesh_less__3_comma__3__greater__wrapper::default_GetWidth)
            , ( bp::arg("rDimension") ) )    
        .def( 
            "IsMeshChanging"
            , (bool ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::IsMeshChanging ) )    
        .def( 
            "IsMeshOnDisk"
            , (bool ( ::AbstractMesh<3, 3>::* )(  )const)( &::AbstractMesh< 3, 3 >::IsMeshOnDisk ) )    
        .def( 
            "PermuteNodes"
            , (void ( ::AbstractMesh<3, 3>::* )(  ))(&::AbstractMesh< 3, 3 >::PermuteNodes)
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_PermuteNodes) )    
        .def( 
            "ReadNodesPerProcessorFile"
            , (void ( ::AbstractMesh<3, 3>::* )( ::std::string const & ))(&::AbstractMesh< 3, 3 >::ReadNodesPerProcessorFile)
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( ::std::string const & ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_ReadNodesPerProcessorFile)
            , ( bp::arg("rNodesPerProcessorFile") ) )    
        .def( 
            "RefreshMesh"
            , (void ( ::AbstractMesh<3, 3>::* )(  ))(&::AbstractMesh< 3, 3 >::RefreshMesh)
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_RefreshMesh) )    
        .def( 
            "Rotate"
            , (void ( ::AbstractMesh<3, 3>::* )( ::boost::numeric::ublas::c_matrix< double, 3, 3 > ))(&::AbstractMesh< 3, 3 >::Rotate)
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( ::boost::numeric::ublas::c_matrix< double, 3, 3 > ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_Rotate)
            , ( bp::arg("rotationMatrix") ) )    
        .def( 
            "Rotate"
            , (void ( ::AbstractMesh<3, 3>::* )( ::boost::numeric::ublas::c_vector< double, 3 >,double ))( &::AbstractMesh< 3, 3 >::Rotate )
            , ( bp::arg("axis"), bp::arg("angle") ) )    
        .def( 
            "Rotate"
            , (void ( ::AbstractMesh<3, 3>::* )( double ))( &::AbstractMesh< 3, 3 >::Rotate )
            , ( bp::arg("theta") ) )    
        .def( 
            "RotateX"
            , (void ( ::AbstractMesh<3, 3>::* )( double const ))( &::AbstractMesh< 3, 3 >::RotateX )
            , ( bp::arg("theta") ) )    
        .def( 
            "RotateY"
            , (void ( ::AbstractMesh<3, 3>::* )( double const ))( &::AbstractMesh< 3, 3 >::RotateY )
            , ( bp::arg("theta") ) )    
        .def( 
            "RotateZ"
            , (void ( ::AbstractMesh<3, 3>::* )( double const ))( &::AbstractMesh< 3, 3 >::RotateZ )
            , ( bp::arg("theta") ) )    
        .def( 
            "Scale"
            , (void ( ::AbstractMesh<3, 3>::* )( double const,double const,double const ))(&::AbstractMesh< 3, 3 >::Scale)
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( double const,double const,double const ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_Scale)
            , ( bp::arg("xFactor")=1., bp::arg("yFactor")=1., bp::arg("zFactor")=1. ) )    
        .def( 
            "SetDistributedVectorFactory"
            , (void ( ::AbstractMesh<3, 3>::* )( ::DistributedVectorFactory * ))(&::AbstractMesh< 3, 3 >::SetDistributedVectorFactory)
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( ::DistributedVectorFactory * ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_SetDistributedVectorFactory)
            , ( bp::arg("pFactory") ) )    
        .def( 
            "SetElementOwnerships"
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )(  ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_SetElementOwnerships) )    
        .def( 
            "SetMeshHasChangedSinceLoading"
            , (void ( ::AbstractMesh<3, 3>::* )(  ))( &::AbstractMesh< 3, 3 >::SetMeshHasChangedSinceLoading ) )    
        .def( 
            "Translate"
            , (void ( ::AbstractMesh<3, 3>::* )( ::boost::numeric::ublas::c_vector< double, 3 > const & ))(&::AbstractMesh< 3, 3 >::Translate)
            , (void ( AbstractMesh_less__3_comma__3__greater__wrapper::* )( ::boost::numeric::ublas::c_vector< double, 3 > const & ))(&AbstractMesh_less__3_comma__3__greater__wrapper::default_Translate)
            , ( bp::arg("rDisplacement") ) )    
        .def( 
            "Translate"
            , (void ( ::AbstractMesh<3, 3>::* )( double const,double const,double const ))( &::AbstractMesh< 3, 3 >::Translate )
            , ( bp::arg("xMovement")=0., bp::arg("yMovement")=0., bp::arg("zMovement")=0. ) );

}
