namespace py = pybind11;

#ifndef CylindricalHoneycombVertexMeshGenerator_hpp__pyplusplus_wrapper
#define CylindricalHoneycombVertexMeshGenerator_hpp__pyplusplus_wrapper
void register_CylindricalHoneycombVertexMeshGenerator_class(py::module &m);
#endif // CylindricalHoneycombVertexMeshGenerator_hpp__pyplusplus_wrapper
