namespace py = pybind11;

#ifndef AbstractNonlinearEllipticPde3_hpp__pyplusplus_wrapper
#define AbstractNonlinearEllipticPde3_hpp__pyplusplus_wrapper
void register_AbstractNonlinearEllipticPde3_class(py::module &m);
#endif // AbstractNonlinearEllipticPde3_hpp__pyplusplus_wrapper
