// This file has been generated by Py++.


/*

Copyright (c) 2005-2017, University of Oxford.
All rights reserved.

University of Oxford means the Chancellor, Masters and Scholars of the
University of Oxford, having an administrative office at Wellington
Square, Oxford OX1 2JD, UK.

This file is part of Chaste.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
 * Neither the name of the University of Oxford nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#include "boost/python.hpp"
#include "wrapper_header_collection.hpp"
#include "AbstractNonlinearEllipticPde3.pypp.hpp"

namespace bp = boost::python;

struct AbstractNonlinearEllipticPde_less__3__greater__wrapper : AbstractNonlinearEllipticPde< 3 >, bp::wrapper< AbstractNonlinearEllipticPde< 3 > > {

    AbstractNonlinearEllipticPde_less__3__greater__wrapper()
    : AbstractNonlinearEllipticPde<3>()
      , bp::wrapper< AbstractNonlinearEllipticPde< 3 > >(){
        // null constructor
        
    }

    virtual ::boost::numeric::ublas::c_matrix< double, 3, 3 > ComputeDiffusionTerm( ::ChastePoint< 3 > const & rX, double u ){
        bp::override func_ComputeDiffusionTerm = this->get_override( "ComputeDiffusionTerm" );
        return func_ComputeDiffusionTerm( boost::ref(rX), u );
    }

    virtual ::boost::numeric::ublas::c_matrix< double, 3, 3 > ComputeDiffusionTermPrime( ::ChastePoint< 3 > const & rX, double u ){
        bp::override func_ComputeDiffusionTermPrime = this->get_override( "ComputeDiffusionTermPrime" );
        return func_ComputeDiffusionTermPrime( boost::ref(rX), u );
    }

    virtual double ComputeLinearSourceTerm( ::ChastePoint< 3 > const & rX ){
        bp::override func_ComputeLinearSourceTerm = this->get_override( "ComputeLinearSourceTerm" );
        return func_ComputeLinearSourceTerm( boost::ref(rX) );
    }

    virtual double ComputeNonlinearSourceTerm( ::ChastePoint< 3 > const & rX, double u ){
        bp::override func_ComputeNonlinearSourceTerm = this->get_override( "ComputeNonlinearSourceTerm" );
        return func_ComputeNonlinearSourceTerm( boost::ref(rX), u );
    }

    virtual double ComputeNonlinearSourceTermPrime( ::ChastePoint< 3 > const & rX, double u ){
        bp::override func_ComputeNonlinearSourceTermPrime = this->get_override( "ComputeNonlinearSourceTermPrime" );
        return func_ComputeNonlinearSourceTermPrime( boost::ref(rX), u );
    }

};

void register_AbstractNonlinearEllipticPde3_class(){

    bp::class_< AbstractNonlinearEllipticPde_less__3__greater__wrapper, boost::noncopyable >( "AbstractNonlinearEllipticPde3" )    
        .def( 
            "ComputeDiffusionTerm"
            , bp::pure_virtual( (::boost::numeric::ublas::c_matrix< double, 3, 3 > ( ::AbstractNonlinearEllipticPde<3>::* )( ::ChastePoint< 3 > const &,double ))(&::AbstractNonlinearEllipticPde< 3 >::ComputeDiffusionTerm) )
            , ( bp::arg("rX"), bp::arg("u") ) )    
        .def( 
            "ComputeDiffusionTermPrime"
            , bp::pure_virtual( (::boost::numeric::ublas::c_matrix< double, 3, 3 > ( ::AbstractNonlinearEllipticPde<3>::* )( ::ChastePoint< 3 > const &,double ))(&::AbstractNonlinearEllipticPde< 3 >::ComputeDiffusionTermPrime) )
            , ( bp::arg("rX"), bp::arg("u") ) )    
        .def( 
            "ComputeLinearSourceTerm"
            , bp::pure_virtual( (double ( ::AbstractNonlinearEllipticPde<3>::* )( ::ChastePoint< 3 > const & ))(&::AbstractNonlinearEllipticPde< 3 >::ComputeLinearSourceTerm) )
            , ( bp::arg("rX") ) )    
        .def( 
            "ComputeNonlinearSourceTerm"
            , bp::pure_virtual( (double ( ::AbstractNonlinearEllipticPde<3>::* )( ::ChastePoint< 3 > const &,double ))(&::AbstractNonlinearEllipticPde< 3 >::ComputeNonlinearSourceTerm) )
            , ( bp::arg("rX"), bp::arg("u") ) )    
        .def( 
            "ComputeNonlinearSourceTermPrime"
            , bp::pure_virtual( (double ( ::AbstractNonlinearEllipticPde<3>::* )( ::ChastePoint< 3 > const &,double ))(&::AbstractNonlinearEllipticPde< 3 >::ComputeNonlinearSourceTermPrime) )
            , ( bp::arg("rX"), bp::arg("u") ) );

}
