namespace py = pybind11;

#ifndef AbstractLinearParabolicPde3_3_hpp__pyplusplus_wrapper
#define AbstractLinearParabolicPde3_3_hpp__pyplusplus_wrapper
void register_AbstractLinearParabolicPde3_3_class(py::module &m);
#endif // AbstractLinearParabolicPde3_3_hpp__pyplusplus_wrapper
